-- ==============================================================
-- RTL generated by Vitis HLS - High-Level Synthesis from C, C++ and OpenCL v2022.1 (64-bit)
-- Version: 2022.1
-- Copyright (C) Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
-- 
-- ===========================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity dut is
generic (
    C_M_AXI_GMEM_ADDR_WIDTH : INTEGER := 64;
    C_M_AXI_GMEM_ID_WIDTH : INTEGER := 1;
    C_M_AXI_GMEM_AWUSER_WIDTH : INTEGER := 1;
    C_M_AXI_GMEM_DATA_WIDTH : INTEGER := 32;
    C_M_AXI_GMEM_WUSER_WIDTH : INTEGER := 1;
    C_M_AXI_GMEM_ARUSER_WIDTH : INTEGER := 1;
    C_M_AXI_GMEM_RUSER_WIDTH : INTEGER := 1;
    C_M_AXI_GMEM_BUSER_WIDTH : INTEGER := 1;
    C_S_AXI_CONTROL_ADDR_WIDTH : INTEGER := 6;
    C_S_AXI_CONTROL_DATA_WIDTH : INTEGER := 32;
    C_M_AXI_GMEM_USER_VALUE : INTEGER := 0;
    C_M_AXI_GMEM_PROT_VALUE : INTEGER := 0;
    C_M_AXI_GMEM_CACHE_VALUE : INTEGER := 3 );
port (
    ap_clk : IN STD_LOGIC;
    ap_rst_n : IN STD_LOGIC;
    ap_start : IN STD_LOGIC;
    ap_done : OUT STD_LOGIC;
    ap_idle : OUT STD_LOGIC;
    ap_ready : OUT STD_LOGIC;
    m_axi_gmem_AWVALID : OUT STD_LOGIC;
    m_axi_gmem_AWREADY : IN STD_LOGIC;
    m_axi_gmem_AWADDR : OUT STD_LOGIC_VECTOR (C_M_AXI_GMEM_ADDR_WIDTH-1 downto 0);
    m_axi_gmem_AWID : OUT STD_LOGIC_VECTOR (C_M_AXI_GMEM_ID_WIDTH-1 downto 0);
    m_axi_gmem_AWLEN : OUT STD_LOGIC_VECTOR (7 downto 0);
    m_axi_gmem_AWSIZE : OUT STD_LOGIC_VECTOR (2 downto 0);
    m_axi_gmem_AWBURST : OUT STD_LOGIC_VECTOR (1 downto 0);
    m_axi_gmem_AWLOCK : OUT STD_LOGIC_VECTOR (1 downto 0);
    m_axi_gmem_AWCACHE : OUT STD_LOGIC_VECTOR (3 downto 0);
    m_axi_gmem_AWPROT : OUT STD_LOGIC_VECTOR (2 downto 0);
    m_axi_gmem_AWQOS : OUT STD_LOGIC_VECTOR (3 downto 0);
    m_axi_gmem_AWREGION : OUT STD_LOGIC_VECTOR (3 downto 0);
    m_axi_gmem_AWUSER : OUT STD_LOGIC_VECTOR (C_M_AXI_GMEM_AWUSER_WIDTH-1 downto 0);
    m_axi_gmem_WVALID : OUT STD_LOGIC;
    m_axi_gmem_WREADY : IN STD_LOGIC;
    m_axi_gmem_WDATA : OUT STD_LOGIC_VECTOR (C_M_AXI_GMEM_DATA_WIDTH-1 downto 0);
    m_axi_gmem_WSTRB : OUT STD_LOGIC_VECTOR (C_M_AXI_GMEM_DATA_WIDTH/8-1 downto 0);
    m_axi_gmem_WLAST : OUT STD_LOGIC;
    m_axi_gmem_WID : OUT STD_LOGIC_VECTOR (C_M_AXI_GMEM_ID_WIDTH-1 downto 0);
    m_axi_gmem_WUSER : OUT STD_LOGIC_VECTOR (C_M_AXI_GMEM_WUSER_WIDTH-1 downto 0);
    m_axi_gmem_ARVALID : OUT STD_LOGIC;
    m_axi_gmem_ARREADY : IN STD_LOGIC;
    m_axi_gmem_ARADDR : OUT STD_LOGIC_VECTOR (C_M_AXI_GMEM_ADDR_WIDTH-1 downto 0);
    m_axi_gmem_ARID : OUT STD_LOGIC_VECTOR (C_M_AXI_GMEM_ID_WIDTH-1 downto 0);
    m_axi_gmem_ARLEN : OUT STD_LOGIC_VECTOR (7 downto 0);
    m_axi_gmem_ARSIZE : OUT STD_LOGIC_VECTOR (2 downto 0);
    m_axi_gmem_ARBURST : OUT STD_LOGIC_VECTOR (1 downto 0);
    m_axi_gmem_ARLOCK : OUT STD_LOGIC_VECTOR (1 downto 0);
    m_axi_gmem_ARCACHE : OUT STD_LOGIC_VECTOR (3 downto 0);
    m_axi_gmem_ARPROT : OUT STD_LOGIC_VECTOR (2 downto 0);
    m_axi_gmem_ARQOS : OUT STD_LOGIC_VECTOR (3 downto 0);
    m_axi_gmem_ARREGION : OUT STD_LOGIC_VECTOR (3 downto 0);
    m_axi_gmem_ARUSER : OUT STD_LOGIC_VECTOR (C_M_AXI_GMEM_ARUSER_WIDTH-1 downto 0);
    m_axi_gmem_RVALID : IN STD_LOGIC;
    m_axi_gmem_RREADY : OUT STD_LOGIC;
    m_axi_gmem_RDATA : IN STD_LOGIC_VECTOR (C_M_AXI_GMEM_DATA_WIDTH-1 downto 0);
    m_axi_gmem_RLAST : IN STD_LOGIC;
    m_axi_gmem_RID : IN STD_LOGIC_VECTOR (C_M_AXI_GMEM_ID_WIDTH-1 downto 0);
    m_axi_gmem_RUSER : IN STD_LOGIC_VECTOR (C_M_AXI_GMEM_RUSER_WIDTH-1 downto 0);
    m_axi_gmem_RRESP : IN STD_LOGIC_VECTOR (1 downto 0);
    m_axi_gmem_BVALID : IN STD_LOGIC;
    m_axi_gmem_BREADY : OUT STD_LOGIC;
    m_axi_gmem_BRESP : IN STD_LOGIC_VECTOR (1 downto 0);
    m_axi_gmem_BID : IN STD_LOGIC_VECTOR (C_M_AXI_GMEM_ID_WIDTH-1 downto 0);
    m_axi_gmem_BUSER : IN STD_LOGIC_VECTOR (C_M_AXI_GMEM_BUSER_WIDTH-1 downto 0);
    s_axi_control_AWVALID : IN STD_LOGIC;
    s_axi_control_AWREADY : OUT STD_LOGIC;
    s_axi_control_AWADDR : IN STD_LOGIC_VECTOR (C_S_AXI_CONTROL_ADDR_WIDTH-1 downto 0);
    s_axi_control_WVALID : IN STD_LOGIC;
    s_axi_control_WREADY : OUT STD_LOGIC;
    s_axi_control_WDATA : IN STD_LOGIC_VECTOR (C_S_AXI_CONTROL_DATA_WIDTH-1 downto 0);
    s_axi_control_WSTRB : IN STD_LOGIC_VECTOR (C_S_AXI_CONTROL_DATA_WIDTH/8-1 downto 0);
    s_axi_control_ARVALID : IN STD_LOGIC;
    s_axi_control_ARREADY : OUT STD_LOGIC;
    s_axi_control_ARADDR : IN STD_LOGIC_VECTOR (C_S_AXI_CONTROL_ADDR_WIDTH-1 downto 0);
    s_axi_control_RVALID : OUT STD_LOGIC;
    s_axi_control_RREADY : IN STD_LOGIC;
    s_axi_control_RDATA : OUT STD_LOGIC_VECTOR (C_S_AXI_CONTROL_DATA_WIDTH-1 downto 0);
    s_axi_control_RRESP : OUT STD_LOGIC_VECTOR (1 downto 0);
    s_axi_control_BVALID : OUT STD_LOGIC;
    s_axi_control_BREADY : IN STD_LOGIC;
    s_axi_control_BRESP : OUT STD_LOGIC_VECTOR (1 downto 0) );
end;


architecture behav of dut is 
    attribute CORE_GENERATION_INFO : STRING;
    attribute CORE_GENERATION_INFO of behav : architecture is
    "dut_dut,hls_ip_2022_1,{HLS_INPUT_TYPE=cxx,HLS_INPUT_FLOAT=0,HLS_INPUT_FIXED=0,HLS_INPUT_PART=xc7z020-clg400-1,HLS_INPUT_CLOCK=7.600000,HLS_INPUT_ARCH=others,HLS_SYN_CLOCK=5.548000,HLS_SYN_LAT=-1,HLS_SYN_TPT=none,HLS_SYN_MEM=0,HLS_SYN_DSP=0,HLS_SYN_FF=6158,HLS_SYN_LUT=7546,HLS_VERSION=2022_1}";
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_logic_0 : STD_LOGIC := '0';
    constant ap_ST_fsm_state1 : STD_LOGIC_VECTOR (13 downto 0) := "00000000000001";
    constant ap_ST_fsm_state2 : STD_LOGIC_VECTOR (13 downto 0) := "00000000000010";
    constant ap_ST_fsm_state3 : STD_LOGIC_VECTOR (13 downto 0) := "00000000000100";
    constant ap_ST_fsm_state4 : STD_LOGIC_VECTOR (13 downto 0) := "00000000001000";
    constant ap_ST_fsm_state5 : STD_LOGIC_VECTOR (13 downto 0) := "00000000010000";
    constant ap_ST_fsm_state6 : STD_LOGIC_VECTOR (13 downto 0) := "00000000100000";
    constant ap_ST_fsm_state7 : STD_LOGIC_VECTOR (13 downto 0) := "00000001000000";
    constant ap_ST_fsm_state8 : STD_LOGIC_VECTOR (13 downto 0) := "00000010000000";
    constant ap_ST_fsm_state9 : STD_LOGIC_VECTOR (13 downto 0) := "00000100000000";
    constant ap_ST_fsm_state10 : STD_LOGIC_VECTOR (13 downto 0) := "00001000000000";
    constant ap_ST_fsm_state11 : STD_LOGIC_VECTOR (13 downto 0) := "00010000000000";
    constant ap_ST_fsm_state12 : STD_LOGIC_VECTOR (13 downto 0) := "00100000000000";
    constant ap_ST_fsm_state13 : STD_LOGIC_VECTOR (13 downto 0) := "01000000000000";
    constant ap_ST_fsm_state14 : STD_LOGIC_VECTOR (13 downto 0) := "10000000000000";
    constant ap_const_lv32_0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    constant ap_const_boolean_1 : BOOLEAN := true;
    constant ap_const_lv32_4 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000100";
    constant ap_const_lv32_B : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001011";
    constant ap_const_lv32_1 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000001";
    constant ap_const_lv32_2 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000010";
    constant ap_const_lv32_5 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000101";
    constant ap_const_lv32_6 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000110";
    constant ap_const_lv1_1 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_lv32_7 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000111";
    constant C_S_AXI_DATA_WIDTH : INTEGER range 63 downto 0 := 20;
    constant C_M_AXI_DATA_WIDTH : INTEGER range 63 downto 0 := 20;
    constant ap_const_lv32_3 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000011";
    constant ap_const_lv32_C : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001100";
    constant ap_const_lv32_D : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001101";
    constant ap_const_lv1_0 : STD_LOGIC_VECTOR (0 downto 0) := "0";
    constant ap_const_lv2_0 : STD_LOGIC_VECTOR (1 downto 0) := "00";
    constant ap_const_boolean_0 : BOOLEAN := false;
    constant ap_const_lv64_2 : STD_LOGIC_VECTOR (63 downto 0) := "0000000000000000000000000000000000000000000000000000000000000010";
    constant ap_const_lv65_1745D1746 : STD_LOGIC_VECTOR (64 downto 0) := "00000000000000000000000000000000101110100010111010001011101000110";
    constant ap_const_lv32_1F : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000011111";
    constant ap_const_lv32_24 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000100100";
    constant ap_const_lv32_40 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000001000000";
    constant ap_const_lv65_0 : STD_LOGIC_VECTOR (64 downto 0) := "00000000000000000000000000000000000000000000000000000000000000000";
    constant ap_const_lv29_0 : STD_LOGIC_VECTOR (28 downto 0) := "00000000000000000000000000000";
    constant ap_const_lv29_1FFFFFFF : STD_LOGIC_VECTOR (28 downto 0) := "11111111111111111111111111111";

    signal ap_rst_n_inv : STD_LOGIC;
    signal ap_CS_fsm : STD_LOGIC_VECTOR (13 downto 0) := "00000000000001";
    attribute fsm_encoding : string;
    attribute fsm_encoding of ap_CS_fsm : signal is "none";
    signal ap_CS_fsm_state1 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state1 : signal is "none";
    signal src_buff : STD_LOGIC_VECTOR (63 downto 0);
    signal src_sz : STD_LOGIC_VECTOR (31 downto 0);
    signal dst_buff : STD_LOGIC_VECTOR (63 downto 0);
    signal gmem_blk_n_AR : STD_LOGIC;
    signal ap_CS_fsm_state5 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state5 : signal is "none";
    signal gmem_blk_n_R : STD_LOGIC;
    signal ap_CS_fsm_state12 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state12 : signal is "none";
    signal dst_buff_read_reg_254 : STD_LOGIC_VECTOR (63 downto 0);
    signal ap_CS_fsm_state2 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state2 : signal is "none";
    signal src_buff_read_reg_260 : STD_LOGIC_VECTOR (63 downto 0);
    signal add_ln41_fu_173_p2 : STD_LOGIC_VECTOR (63 downto 0);
    signal add_ln41_reg_266 : STD_LOGIC_VECTOR (63 downto 0);
    signal tmp_reg_277 : STD_LOGIC_VECTOR (0 downto 0);
    signal gmem_addr_1_reg_283 : STD_LOGIC_VECTOR (63 downto 0);
    signal ap_CS_fsm_state3 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state3 : signal is "none";
    signal grp_fu_183_p2 : STD_LOGIC_VECTOR (64 downto 0);
    signal mul_reg_289 : STD_LOGIC_VECTOR (64 downto 0);
    signal ap_CS_fsm_state6 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state6 : signal is "none";
    signal tmp_4_reg_294 : STD_LOGIC_VECTOR (28 downto 0);
    signal neg_mul_fu_212_p2 : STD_LOGIC_VECTOR (64 downto 0);
    signal neg_mul_reg_300 : STD_LOGIC_VECTOR (64 downto 0);
    signal ap_CS_fsm_state7 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state7 : signal is "none";
    signal sub_fu_244_p2 : STD_LOGIC_VECTOR (28 downto 0);
    signal sub_reg_305 : STD_LOGIC_VECTOR (28 downto 0);
    signal ap_CS_fsm_state8 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state8 : signal is "none";
    signal next_col_idx_V_fu_250_p1 : STD_LOGIC_VECTOR (2 downto 0);
    signal next_col_idx_V_reg_310 : STD_LOGIC_VECTOR (2 downto 0);
    signal ptr_col_address0 : STD_LOGIC_VECTOR (2 downto 0);
    signal ptr_col_ce0 : STD_LOGIC;
    signal ptr_col_we0 : STD_LOGIC;
    signal ptr_col_d0 : STD_LOGIC_VECTOR (31 downto 0);
    signal ptr_col_q0 : STD_LOGIC_VECTOR (31 downto 0);
    signal ptr_col_ce1 : STD_LOGIC;
    signal ptr_col_we1 : STD_LOGIC;
    signal ptr_col_q1 : STD_LOGIC_VECTOR (31 downto 0);
    signal ptr_col2_address0 : STD_LOGIC_VECTOR (2 downto 0);
    signal ptr_col2_ce0 : STD_LOGIC;
    signal ptr_col2_we0 : STD_LOGIC;
    signal ptr_col2_d0 : STD_LOGIC_VECTOR (31 downto 0);
    signal ptr_col2_q0 : STD_LOGIC_VECTOR (31 downto 0);
    signal ptr_col2_base_address0 : STD_LOGIC_VECTOR (2 downto 0);
    signal ptr_col2_base_ce0 : STD_LOGIC;
    signal ptr_col2_base_we0 : STD_LOGIC;
    signal ptr_col2_base_d0 : STD_LOGIC_VECTOR (31 downto 0);
    signal ptr_col2_base_q0 : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_dut_Pipeline_1_fu_130_ap_start : STD_LOGIC;
    signal grp_dut_Pipeline_1_fu_130_ap_done : STD_LOGIC;
    signal grp_dut_Pipeline_1_fu_130_ap_idle : STD_LOGIC;
    signal grp_dut_Pipeline_1_fu_130_ap_ready : STD_LOGIC;
    signal grp_dut_Pipeline_1_fu_130_ptr_col_address0 : STD_LOGIC_VECTOR (2 downto 0);
    signal grp_dut_Pipeline_1_fu_130_ptr_col_ce0 : STD_LOGIC;
    signal grp_dut_Pipeline_1_fu_130_ptr_col_we0 : STD_LOGIC;
    signal grp_dut_Pipeline_1_fu_130_ptr_col_d0 : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_dut_Pipeline_2_fu_136_ap_start : STD_LOGIC;
    signal grp_dut_Pipeline_2_fu_136_ap_done : STD_LOGIC;
    signal grp_dut_Pipeline_2_fu_136_ap_idle : STD_LOGIC;
    signal grp_dut_Pipeline_2_fu_136_ap_ready : STD_LOGIC;
    signal grp_dut_Pipeline_2_fu_136_ptr_col2_address0 : STD_LOGIC_VECTOR (2 downto 0);
    signal grp_dut_Pipeline_2_fu_136_ptr_col2_ce0 : STD_LOGIC;
    signal grp_dut_Pipeline_2_fu_136_ptr_col2_we0 : STD_LOGIC;
    signal grp_dut_Pipeline_2_fu_136_ptr_col2_d0 : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_dut_Pipeline_3_fu_142_ap_start : STD_LOGIC;
    signal grp_dut_Pipeline_3_fu_142_ap_done : STD_LOGIC;
    signal grp_dut_Pipeline_3_fu_142_ap_idle : STD_LOGIC;
    signal grp_dut_Pipeline_3_fu_142_ap_ready : STD_LOGIC;
    signal grp_dut_Pipeline_3_fu_142_ptr_col2_base_address0 : STD_LOGIC_VECTOR (2 downto 0);
    signal grp_dut_Pipeline_3_fu_142_ptr_col2_base_ce0 : STD_LOGIC;
    signal grp_dut_Pipeline_3_fu_142_ptr_col2_base_we0 : STD_LOGIC;
    signal grp_dut_Pipeline_3_fu_142_ptr_col2_base_d0 : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_dut_Pipeline_VITIS_LOOP_38_1_fu_148_ap_start : STD_LOGIC;
    signal grp_dut_Pipeline_VITIS_LOOP_38_1_fu_148_ap_done : STD_LOGIC;
    signal grp_dut_Pipeline_VITIS_LOOP_38_1_fu_148_ap_idle : STD_LOGIC;
    signal grp_dut_Pipeline_VITIS_LOOP_38_1_fu_148_ap_ready : STD_LOGIC;
    signal grp_dut_Pipeline_VITIS_LOOP_38_1_fu_148_m_axi_gmem_AWVALID : STD_LOGIC;
    signal grp_dut_Pipeline_VITIS_LOOP_38_1_fu_148_m_axi_gmem_AWADDR : STD_LOGIC_VECTOR (63 downto 0);
    signal grp_dut_Pipeline_VITIS_LOOP_38_1_fu_148_m_axi_gmem_AWID : STD_LOGIC_VECTOR (0 downto 0);
    signal grp_dut_Pipeline_VITIS_LOOP_38_1_fu_148_m_axi_gmem_AWLEN : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_dut_Pipeline_VITIS_LOOP_38_1_fu_148_m_axi_gmem_AWSIZE : STD_LOGIC_VECTOR (2 downto 0);
    signal grp_dut_Pipeline_VITIS_LOOP_38_1_fu_148_m_axi_gmem_AWBURST : STD_LOGIC_VECTOR (1 downto 0);
    signal grp_dut_Pipeline_VITIS_LOOP_38_1_fu_148_m_axi_gmem_AWLOCK : STD_LOGIC_VECTOR (1 downto 0);
    signal grp_dut_Pipeline_VITIS_LOOP_38_1_fu_148_m_axi_gmem_AWCACHE : STD_LOGIC_VECTOR (3 downto 0);
    signal grp_dut_Pipeline_VITIS_LOOP_38_1_fu_148_m_axi_gmem_AWPROT : STD_LOGIC_VECTOR (2 downto 0);
    signal grp_dut_Pipeline_VITIS_LOOP_38_1_fu_148_m_axi_gmem_AWQOS : STD_LOGIC_VECTOR (3 downto 0);
    signal grp_dut_Pipeline_VITIS_LOOP_38_1_fu_148_m_axi_gmem_AWREGION : STD_LOGIC_VECTOR (3 downto 0);
    signal grp_dut_Pipeline_VITIS_LOOP_38_1_fu_148_m_axi_gmem_AWUSER : STD_LOGIC_VECTOR (0 downto 0);
    signal grp_dut_Pipeline_VITIS_LOOP_38_1_fu_148_m_axi_gmem_WVALID : STD_LOGIC;
    signal grp_dut_Pipeline_VITIS_LOOP_38_1_fu_148_m_axi_gmem_WDATA : STD_LOGIC_VECTOR (7 downto 0);
    signal grp_dut_Pipeline_VITIS_LOOP_38_1_fu_148_m_axi_gmem_WSTRB : STD_LOGIC_VECTOR (0 downto 0);
    signal grp_dut_Pipeline_VITIS_LOOP_38_1_fu_148_m_axi_gmem_WLAST : STD_LOGIC;
    signal grp_dut_Pipeline_VITIS_LOOP_38_1_fu_148_m_axi_gmem_WID : STD_LOGIC_VECTOR (0 downto 0);
    signal grp_dut_Pipeline_VITIS_LOOP_38_1_fu_148_m_axi_gmem_WUSER : STD_LOGIC_VECTOR (0 downto 0);
    signal grp_dut_Pipeline_VITIS_LOOP_38_1_fu_148_m_axi_gmem_ARVALID : STD_LOGIC;
    signal grp_dut_Pipeline_VITIS_LOOP_38_1_fu_148_m_axi_gmem_ARADDR : STD_LOGIC_VECTOR (63 downto 0);
    signal grp_dut_Pipeline_VITIS_LOOP_38_1_fu_148_m_axi_gmem_ARID : STD_LOGIC_VECTOR (0 downto 0);
    signal grp_dut_Pipeline_VITIS_LOOP_38_1_fu_148_m_axi_gmem_ARLEN : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_dut_Pipeline_VITIS_LOOP_38_1_fu_148_m_axi_gmem_ARSIZE : STD_LOGIC_VECTOR (2 downto 0);
    signal grp_dut_Pipeline_VITIS_LOOP_38_1_fu_148_m_axi_gmem_ARBURST : STD_LOGIC_VECTOR (1 downto 0);
    signal grp_dut_Pipeline_VITIS_LOOP_38_1_fu_148_m_axi_gmem_ARLOCK : STD_LOGIC_VECTOR (1 downto 0);
    signal grp_dut_Pipeline_VITIS_LOOP_38_1_fu_148_m_axi_gmem_ARCACHE : STD_LOGIC_VECTOR (3 downto 0);
    signal grp_dut_Pipeline_VITIS_LOOP_38_1_fu_148_m_axi_gmem_ARPROT : STD_LOGIC_VECTOR (2 downto 0);
    signal grp_dut_Pipeline_VITIS_LOOP_38_1_fu_148_m_axi_gmem_ARQOS : STD_LOGIC_VECTOR (3 downto 0);
    signal grp_dut_Pipeline_VITIS_LOOP_38_1_fu_148_m_axi_gmem_ARREGION : STD_LOGIC_VECTOR (3 downto 0);
    signal grp_dut_Pipeline_VITIS_LOOP_38_1_fu_148_m_axi_gmem_ARUSER : STD_LOGIC_VECTOR (0 downto 0);
    signal grp_dut_Pipeline_VITIS_LOOP_38_1_fu_148_m_axi_gmem_RREADY : STD_LOGIC;
    signal grp_dut_Pipeline_VITIS_LOOP_38_1_fu_148_m_axi_gmem_BREADY : STD_LOGIC;
    signal grp_dut_Pipeline_VITIS_LOOP_38_1_fu_148_ptr_col_address0 : STD_LOGIC_VECTOR (2 downto 0);
    signal grp_dut_Pipeline_VITIS_LOOP_38_1_fu_148_ptr_col_ce0 : STD_LOGIC;
    signal grp_dut_Pipeline_VITIS_LOOP_38_1_fu_148_ptr_col_we0 : STD_LOGIC;
    signal grp_dut_Pipeline_VITIS_LOOP_38_1_fu_148_ptr_col_d0 : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_dut_Pipeline_VITIS_LOOP_38_1_fu_148_ptr_col_address1 : STD_LOGIC_VECTOR (2 downto 0);
    signal grp_dut_Pipeline_VITIS_LOOP_38_1_fu_148_ptr_col_ce1 : STD_LOGIC;
    signal grp_dut_Pipeline_VITIS_LOOP_38_1_fu_148_ptr_col_we1 : STD_LOGIC;
    signal grp_dut_Pipeline_VITIS_LOOP_38_1_fu_148_ptr_col_d1 : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_dut_Pipeline_VITIS_LOOP_38_1_fu_148_ptr_col2_address0 : STD_LOGIC_VECTOR (2 downto 0);
    signal grp_dut_Pipeline_VITIS_LOOP_38_1_fu_148_ptr_col2_ce0 : STD_LOGIC;
    signal grp_dut_Pipeline_VITIS_LOOP_38_1_fu_148_ptr_col2_we0 : STD_LOGIC;
    signal grp_dut_Pipeline_VITIS_LOOP_38_1_fu_148_ptr_col2_d0 : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_dut_Pipeline_VITIS_LOOP_38_1_fu_148_ptr_col2_base_address0 : STD_LOGIC_VECTOR (2 downto 0);
    signal grp_dut_Pipeline_VITIS_LOOP_38_1_fu_148_ptr_col2_base_ce0 : STD_LOGIC;
    signal grp_dut_Pipeline_VITIS_LOOP_38_1_fu_148_ptr_col2_base_we0 : STD_LOGIC;
    signal grp_dut_Pipeline_VITIS_LOOP_38_1_fu_148_ptr_col2_base_d0 : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_dut_Pipeline_VITIS_LOOP_73_2_fu_160_ap_start : STD_LOGIC;
    signal grp_dut_Pipeline_VITIS_LOOP_73_2_fu_160_ap_done : STD_LOGIC;
    signal grp_dut_Pipeline_VITIS_LOOP_73_2_fu_160_ap_idle : STD_LOGIC;
    signal grp_dut_Pipeline_VITIS_LOOP_73_2_fu_160_ap_ready : STD_LOGIC;
    signal grp_dut_Pipeline_VITIS_LOOP_73_2_fu_160_m_axi_gmem_AWVALID : STD_LOGIC;
    signal grp_dut_Pipeline_VITIS_LOOP_73_2_fu_160_m_axi_gmem_AWADDR : STD_LOGIC_VECTOR (63 downto 0);
    signal grp_dut_Pipeline_VITIS_LOOP_73_2_fu_160_m_axi_gmem_AWID : STD_LOGIC_VECTOR (0 downto 0);
    signal grp_dut_Pipeline_VITIS_LOOP_73_2_fu_160_m_axi_gmem_AWLEN : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_dut_Pipeline_VITIS_LOOP_73_2_fu_160_m_axi_gmem_AWSIZE : STD_LOGIC_VECTOR (2 downto 0);
    signal grp_dut_Pipeline_VITIS_LOOP_73_2_fu_160_m_axi_gmem_AWBURST : STD_LOGIC_VECTOR (1 downto 0);
    signal grp_dut_Pipeline_VITIS_LOOP_73_2_fu_160_m_axi_gmem_AWLOCK : STD_LOGIC_VECTOR (1 downto 0);
    signal grp_dut_Pipeline_VITIS_LOOP_73_2_fu_160_m_axi_gmem_AWCACHE : STD_LOGIC_VECTOR (3 downto 0);
    signal grp_dut_Pipeline_VITIS_LOOP_73_2_fu_160_m_axi_gmem_AWPROT : STD_LOGIC_VECTOR (2 downto 0);
    signal grp_dut_Pipeline_VITIS_LOOP_73_2_fu_160_m_axi_gmem_AWQOS : STD_LOGIC_VECTOR (3 downto 0);
    signal grp_dut_Pipeline_VITIS_LOOP_73_2_fu_160_m_axi_gmem_AWREGION : STD_LOGIC_VECTOR (3 downto 0);
    signal grp_dut_Pipeline_VITIS_LOOP_73_2_fu_160_m_axi_gmem_AWUSER : STD_LOGIC_VECTOR (0 downto 0);
    signal grp_dut_Pipeline_VITIS_LOOP_73_2_fu_160_m_axi_gmem_WVALID : STD_LOGIC;
    signal grp_dut_Pipeline_VITIS_LOOP_73_2_fu_160_m_axi_gmem_WDATA : STD_LOGIC_VECTOR (7 downto 0);
    signal grp_dut_Pipeline_VITIS_LOOP_73_2_fu_160_m_axi_gmem_WSTRB : STD_LOGIC_VECTOR (0 downto 0);
    signal grp_dut_Pipeline_VITIS_LOOP_73_2_fu_160_m_axi_gmem_WLAST : STD_LOGIC;
    signal grp_dut_Pipeline_VITIS_LOOP_73_2_fu_160_m_axi_gmem_WID : STD_LOGIC_VECTOR (0 downto 0);
    signal grp_dut_Pipeline_VITIS_LOOP_73_2_fu_160_m_axi_gmem_WUSER : STD_LOGIC_VECTOR (0 downto 0);
    signal grp_dut_Pipeline_VITIS_LOOP_73_2_fu_160_m_axi_gmem_ARVALID : STD_LOGIC;
    signal grp_dut_Pipeline_VITIS_LOOP_73_2_fu_160_m_axi_gmem_ARADDR : STD_LOGIC_VECTOR (63 downto 0);
    signal grp_dut_Pipeline_VITIS_LOOP_73_2_fu_160_m_axi_gmem_ARID : STD_LOGIC_VECTOR (0 downto 0);
    signal grp_dut_Pipeline_VITIS_LOOP_73_2_fu_160_m_axi_gmem_ARLEN : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_dut_Pipeline_VITIS_LOOP_73_2_fu_160_m_axi_gmem_ARSIZE : STD_LOGIC_VECTOR (2 downto 0);
    signal grp_dut_Pipeline_VITIS_LOOP_73_2_fu_160_m_axi_gmem_ARBURST : STD_LOGIC_VECTOR (1 downto 0);
    signal grp_dut_Pipeline_VITIS_LOOP_73_2_fu_160_m_axi_gmem_ARLOCK : STD_LOGIC_VECTOR (1 downto 0);
    signal grp_dut_Pipeline_VITIS_LOOP_73_2_fu_160_m_axi_gmem_ARCACHE : STD_LOGIC_VECTOR (3 downto 0);
    signal grp_dut_Pipeline_VITIS_LOOP_73_2_fu_160_m_axi_gmem_ARPROT : STD_LOGIC_VECTOR (2 downto 0);
    signal grp_dut_Pipeline_VITIS_LOOP_73_2_fu_160_m_axi_gmem_ARQOS : STD_LOGIC_VECTOR (3 downto 0);
    signal grp_dut_Pipeline_VITIS_LOOP_73_2_fu_160_m_axi_gmem_ARREGION : STD_LOGIC_VECTOR (3 downto 0);
    signal grp_dut_Pipeline_VITIS_LOOP_73_2_fu_160_m_axi_gmem_ARUSER : STD_LOGIC_VECTOR (0 downto 0);
    signal grp_dut_Pipeline_VITIS_LOOP_73_2_fu_160_m_axi_gmem_RREADY : STD_LOGIC;
    signal grp_dut_Pipeline_VITIS_LOOP_73_2_fu_160_m_axi_gmem_BREADY : STD_LOGIC;
    signal grp_dut_Pipeline_VITIS_LOOP_73_2_fu_160_ptr_col_address0 : STD_LOGIC_VECTOR (2 downto 0);
    signal grp_dut_Pipeline_VITIS_LOOP_73_2_fu_160_ptr_col_ce0 : STD_LOGIC;
    signal grp_dut_Pipeline_VITIS_LOOP_73_2_fu_160_ptr_col_we0 : STD_LOGIC;
    signal grp_dut_Pipeline_VITIS_LOOP_73_2_fu_160_ptr_col_d0 : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_dut_Pipeline_VITIS_LOOP_73_2_fu_160_ptr_col2_address0 : STD_LOGIC_VECTOR (2 downto 0);
    signal grp_dut_Pipeline_VITIS_LOOP_73_2_fu_160_ptr_col2_ce0 : STD_LOGIC;
    signal grp_dut_Pipeline_VITIS_LOOP_73_2_fu_160_ptr_col2_we0 : STD_LOGIC;
    signal grp_dut_Pipeline_VITIS_LOOP_73_2_fu_160_ptr_col2_d0 : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_dut_Pipeline_VITIS_LOOP_73_2_fu_160_ptr_col2_base_address0 : STD_LOGIC_VECTOR (2 downto 0);
    signal grp_dut_Pipeline_VITIS_LOOP_73_2_fu_160_ptr_col2_base_ce0 : STD_LOGIC;
    signal gmem_AWVALID : STD_LOGIC;
    signal gmem_AWREADY : STD_LOGIC;
    signal gmem_AWADDR : STD_LOGIC_VECTOR (63 downto 0);
    signal gmem_AWLEN : STD_LOGIC_VECTOR (31 downto 0);
    signal gmem_WVALID : STD_LOGIC;
    signal gmem_WREADY : STD_LOGIC;
    signal gmem_WDATA : STD_LOGIC_VECTOR (7 downto 0);
    signal gmem_WSTRB : STD_LOGIC_VECTOR (0 downto 0);
    signal gmem_ARVALID : STD_LOGIC;
    signal gmem_ARREADY : STD_LOGIC;
    signal gmem_ARADDR : STD_LOGIC_VECTOR (63 downto 0);
    signal gmem_ARLEN : STD_LOGIC_VECTOR (31 downto 0);
    signal gmem_RVALID : STD_LOGIC;
    signal gmem_RREADY : STD_LOGIC;
    signal gmem_RDATA : STD_LOGIC_VECTOR (7 downto 0);
    signal gmem_RFIFONUM : STD_LOGIC_VECTOR (10 downto 0);
    signal gmem_BVALID : STD_LOGIC;
    signal gmem_BREADY : STD_LOGIC;
    signal grp_dut_Pipeline_1_fu_130_ap_start_reg : STD_LOGIC := '0';
    signal grp_dut_Pipeline_2_fu_136_ap_start_reg : STD_LOGIC := '0';
    signal grp_dut_Pipeline_3_fu_142_ap_start_reg : STD_LOGIC := '0';
    signal grp_dut_Pipeline_VITIS_LOOP_38_1_fu_148_ap_start_reg : STD_LOGIC := '0';
    signal ap_CS_fsm_state4 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state4 : signal is "none";
    signal grp_dut_Pipeline_VITIS_LOOP_73_2_fu_160_ap_start_reg : STD_LOGIC := '0';
    signal ap_NS_fsm : STD_LOGIC_VECTOR (13 downto 0);
    signal ap_NS_fsm_state13 : STD_LOGIC;
    signal ap_CS_fsm_state14 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state14 : signal is "none";
    signal ap_CS_fsm_state13 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state13 : signal is "none";
    signal ap_block_state2_on_subcall_done : BOOLEAN;
    signal grp_fu_183_p1 : STD_LOGIC_VECTOR (33 downto 0);
    signal tmp_fu_189_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal tmp_3_fu_217_p4 : STD_LOGIC_VECTOR (28 downto 0);
    signal empty_fu_226_p3 : STD_LOGIC_VECTOR (28 downto 0);
    signal neg_ti_fu_232_p2 : STD_LOGIC_VECTOR (28 downto 0);
    signal empty_40_fu_238_p3 : STD_LOGIC_VECTOR (28 downto 0);
    signal grp_fu_183_ce : STD_LOGIC;
    signal ap_ST_fsm_state1_blk : STD_LOGIC;
    signal ap_ST_fsm_state2_blk : STD_LOGIC;
    signal ap_ST_fsm_state3_blk : STD_LOGIC;
    signal ap_ST_fsm_state4_blk : STD_LOGIC;
    signal ap_ST_fsm_state5_blk : STD_LOGIC;
    signal ap_ST_fsm_state6_blk : STD_LOGIC;
    signal ap_ST_fsm_state7_blk : STD_LOGIC;
    signal ap_ST_fsm_state8_blk : STD_LOGIC;
    signal ap_ST_fsm_state9_blk : STD_LOGIC;
    signal ap_ST_fsm_state10_blk : STD_LOGIC;
    signal ap_ST_fsm_state11_blk : STD_LOGIC;
    signal ap_ST_fsm_state12_blk : STD_LOGIC;
    signal ap_ST_fsm_state13_blk : STD_LOGIC;
    signal ap_ST_fsm_state14_blk : STD_LOGIC;
    signal ap_ce_reg : STD_LOGIC;

    component dut_dut_Pipeline_1 IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_idle : OUT STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        ptr_col_address0 : OUT STD_LOGIC_VECTOR (2 downto 0);
        ptr_col_ce0 : OUT STD_LOGIC;
        ptr_col_we0 : OUT STD_LOGIC;
        ptr_col_d0 : OUT STD_LOGIC_VECTOR (31 downto 0) );
    end component;


    component dut_dut_Pipeline_2 IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_idle : OUT STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        ptr_col2_address0 : OUT STD_LOGIC_VECTOR (2 downto 0);
        ptr_col2_ce0 : OUT STD_LOGIC;
        ptr_col2_we0 : OUT STD_LOGIC;
        ptr_col2_d0 : OUT STD_LOGIC_VECTOR (31 downto 0) );
    end component;


    component dut_dut_Pipeline_3 IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_idle : OUT STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        ptr_col2_base_address0 : OUT STD_LOGIC_VECTOR (2 downto 0);
        ptr_col2_base_ce0 : OUT STD_LOGIC;
        ptr_col2_base_we0 : OUT STD_LOGIC;
        ptr_col2_base_d0 : OUT STD_LOGIC_VECTOR (31 downto 0) );
    end component;


    component dut_dut_Pipeline_VITIS_LOOP_38_1 IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_idle : OUT STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        m_axi_gmem_AWVALID : OUT STD_LOGIC;
        m_axi_gmem_AWREADY : IN STD_LOGIC;
        m_axi_gmem_AWADDR : OUT STD_LOGIC_VECTOR (63 downto 0);
        m_axi_gmem_AWID : OUT STD_LOGIC_VECTOR (0 downto 0);
        m_axi_gmem_AWLEN : OUT STD_LOGIC_VECTOR (31 downto 0);
        m_axi_gmem_AWSIZE : OUT STD_LOGIC_VECTOR (2 downto 0);
        m_axi_gmem_AWBURST : OUT STD_LOGIC_VECTOR (1 downto 0);
        m_axi_gmem_AWLOCK : OUT STD_LOGIC_VECTOR (1 downto 0);
        m_axi_gmem_AWCACHE : OUT STD_LOGIC_VECTOR (3 downto 0);
        m_axi_gmem_AWPROT : OUT STD_LOGIC_VECTOR (2 downto 0);
        m_axi_gmem_AWQOS : OUT STD_LOGIC_VECTOR (3 downto 0);
        m_axi_gmem_AWREGION : OUT STD_LOGIC_VECTOR (3 downto 0);
        m_axi_gmem_AWUSER : OUT STD_LOGIC_VECTOR (0 downto 0);
        m_axi_gmem_WVALID : OUT STD_LOGIC;
        m_axi_gmem_WREADY : IN STD_LOGIC;
        m_axi_gmem_WDATA : OUT STD_LOGIC_VECTOR (7 downto 0);
        m_axi_gmem_WSTRB : OUT STD_LOGIC_VECTOR (0 downto 0);
        m_axi_gmem_WLAST : OUT STD_LOGIC;
        m_axi_gmem_WID : OUT STD_LOGIC_VECTOR (0 downto 0);
        m_axi_gmem_WUSER : OUT STD_LOGIC_VECTOR (0 downto 0);
        m_axi_gmem_ARVALID : OUT STD_LOGIC;
        m_axi_gmem_ARREADY : IN STD_LOGIC;
        m_axi_gmem_ARADDR : OUT STD_LOGIC_VECTOR (63 downto 0);
        m_axi_gmem_ARID : OUT STD_LOGIC_VECTOR (0 downto 0);
        m_axi_gmem_ARLEN : OUT STD_LOGIC_VECTOR (31 downto 0);
        m_axi_gmem_ARSIZE : OUT STD_LOGIC_VECTOR (2 downto 0);
        m_axi_gmem_ARBURST : OUT STD_LOGIC_VECTOR (1 downto 0);
        m_axi_gmem_ARLOCK : OUT STD_LOGIC_VECTOR (1 downto 0);
        m_axi_gmem_ARCACHE : OUT STD_LOGIC_VECTOR (3 downto 0);
        m_axi_gmem_ARPROT : OUT STD_LOGIC_VECTOR (2 downto 0);
        m_axi_gmem_ARQOS : OUT STD_LOGIC_VECTOR (3 downto 0);
        m_axi_gmem_ARREGION : OUT STD_LOGIC_VECTOR (3 downto 0);
        m_axi_gmem_ARUSER : OUT STD_LOGIC_VECTOR (0 downto 0);
        m_axi_gmem_RVALID : IN STD_LOGIC;
        m_axi_gmem_RREADY : OUT STD_LOGIC;
        m_axi_gmem_RDATA : IN STD_LOGIC_VECTOR (7 downto 0);
        m_axi_gmem_RLAST : IN STD_LOGIC;
        m_axi_gmem_RID : IN STD_LOGIC_VECTOR (0 downto 0);
        m_axi_gmem_RFIFONUM : IN STD_LOGIC_VECTOR (10 downto 0);
        m_axi_gmem_RUSER : IN STD_LOGIC_VECTOR (0 downto 0);
        m_axi_gmem_RRESP : IN STD_LOGIC_VECTOR (1 downto 0);
        m_axi_gmem_BVALID : IN STD_LOGIC;
        m_axi_gmem_BREADY : OUT STD_LOGIC;
        m_axi_gmem_BRESP : IN STD_LOGIC_VECTOR (1 downto 0);
        m_axi_gmem_BID : IN STD_LOGIC_VECTOR (0 downto 0);
        m_axi_gmem_BUSER : IN STD_LOGIC_VECTOR (0 downto 0);
        src_buff : IN STD_LOGIC_VECTOR (63 downto 0);
        add_ln41 : IN STD_LOGIC_VECTOR (63 downto 0);
        ptr_col_address0 : OUT STD_LOGIC_VECTOR (2 downto 0);
        ptr_col_ce0 : OUT STD_LOGIC;
        ptr_col_we0 : OUT STD_LOGIC;
        ptr_col_d0 : OUT STD_LOGIC_VECTOR (31 downto 0);
        ptr_col_q0 : IN STD_LOGIC_VECTOR (31 downto 0);
        ptr_col_address1 : OUT STD_LOGIC_VECTOR (2 downto 0);
        ptr_col_ce1 : OUT STD_LOGIC;
        ptr_col_we1 : OUT STD_LOGIC;
        ptr_col_d1 : OUT STD_LOGIC_VECTOR (31 downto 0);
        ptr_col_q1 : IN STD_LOGIC_VECTOR (31 downto 0);
        ptr_col2_address0 : OUT STD_LOGIC_VECTOR (2 downto 0);
        ptr_col2_ce0 : OUT STD_LOGIC;
        ptr_col2_we0 : OUT STD_LOGIC;
        ptr_col2_d0 : OUT STD_LOGIC_VECTOR (31 downto 0);
        ptr_col2_base_address0 : OUT STD_LOGIC_VECTOR (2 downto 0);
        ptr_col2_base_ce0 : OUT STD_LOGIC;
        ptr_col2_base_we0 : OUT STD_LOGIC;
        ptr_col2_base_d0 : OUT STD_LOGIC_VECTOR (31 downto 0);
        dst_buff : IN STD_LOGIC_VECTOR (63 downto 0) );
    end component;


    component dut_dut_Pipeline_VITIS_LOOP_73_2 IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_idle : OUT STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        m_axi_gmem_AWVALID : OUT STD_LOGIC;
        m_axi_gmem_AWREADY : IN STD_LOGIC;
        m_axi_gmem_AWADDR : OUT STD_LOGIC_VECTOR (63 downto 0);
        m_axi_gmem_AWID : OUT STD_LOGIC_VECTOR (0 downto 0);
        m_axi_gmem_AWLEN : OUT STD_LOGIC_VECTOR (31 downto 0);
        m_axi_gmem_AWSIZE : OUT STD_LOGIC_VECTOR (2 downto 0);
        m_axi_gmem_AWBURST : OUT STD_LOGIC_VECTOR (1 downto 0);
        m_axi_gmem_AWLOCK : OUT STD_LOGIC_VECTOR (1 downto 0);
        m_axi_gmem_AWCACHE : OUT STD_LOGIC_VECTOR (3 downto 0);
        m_axi_gmem_AWPROT : OUT STD_LOGIC_VECTOR (2 downto 0);
        m_axi_gmem_AWQOS : OUT STD_LOGIC_VECTOR (3 downto 0);
        m_axi_gmem_AWREGION : OUT STD_LOGIC_VECTOR (3 downto 0);
        m_axi_gmem_AWUSER : OUT STD_LOGIC_VECTOR (0 downto 0);
        m_axi_gmem_WVALID : OUT STD_LOGIC;
        m_axi_gmem_WREADY : IN STD_LOGIC;
        m_axi_gmem_WDATA : OUT STD_LOGIC_VECTOR (7 downto 0);
        m_axi_gmem_WSTRB : OUT STD_LOGIC_VECTOR (0 downto 0);
        m_axi_gmem_WLAST : OUT STD_LOGIC;
        m_axi_gmem_WID : OUT STD_LOGIC_VECTOR (0 downto 0);
        m_axi_gmem_WUSER : OUT STD_LOGIC_VECTOR (0 downto 0);
        m_axi_gmem_ARVALID : OUT STD_LOGIC;
        m_axi_gmem_ARREADY : IN STD_LOGIC;
        m_axi_gmem_ARADDR : OUT STD_LOGIC_VECTOR (63 downto 0);
        m_axi_gmem_ARID : OUT STD_LOGIC_VECTOR (0 downto 0);
        m_axi_gmem_ARLEN : OUT STD_LOGIC_VECTOR (31 downto 0);
        m_axi_gmem_ARSIZE : OUT STD_LOGIC_VECTOR (2 downto 0);
        m_axi_gmem_ARBURST : OUT STD_LOGIC_VECTOR (1 downto 0);
        m_axi_gmem_ARLOCK : OUT STD_LOGIC_VECTOR (1 downto 0);
        m_axi_gmem_ARCACHE : OUT STD_LOGIC_VECTOR (3 downto 0);
        m_axi_gmem_ARPROT : OUT STD_LOGIC_VECTOR (2 downto 0);
        m_axi_gmem_ARQOS : OUT STD_LOGIC_VECTOR (3 downto 0);
        m_axi_gmem_ARREGION : OUT STD_LOGIC_VECTOR (3 downto 0);
        m_axi_gmem_ARUSER : OUT STD_LOGIC_VECTOR (0 downto 0);
        m_axi_gmem_RVALID : IN STD_LOGIC;
        m_axi_gmem_RREADY : OUT STD_LOGIC;
        m_axi_gmem_RDATA : IN STD_LOGIC_VECTOR (7 downto 0);
        m_axi_gmem_RLAST : IN STD_LOGIC;
        m_axi_gmem_RID : IN STD_LOGIC_VECTOR (0 downto 0);
        m_axi_gmem_RFIFONUM : IN STD_LOGIC_VECTOR (10 downto 0);
        m_axi_gmem_RUSER : IN STD_LOGIC_VECTOR (0 downto 0);
        m_axi_gmem_RRESP : IN STD_LOGIC_VECTOR (1 downto 0);
        m_axi_gmem_BVALID : IN STD_LOGIC;
        m_axi_gmem_BREADY : OUT STD_LOGIC;
        m_axi_gmem_BRESP : IN STD_LOGIC_VECTOR (1 downto 0);
        m_axi_gmem_BID : IN STD_LOGIC_VECTOR (0 downto 0);
        m_axi_gmem_BUSER : IN STD_LOGIC_VECTOR (0 downto 0);
        next_col_idx_V : IN STD_LOGIC_VECTOR (2 downto 0);
        sub : IN STD_LOGIC_VECTOR (28 downto 0);
        ptr_col_address0 : OUT STD_LOGIC_VECTOR (2 downto 0);
        ptr_col_ce0 : OUT STD_LOGIC;
        ptr_col_we0 : OUT STD_LOGIC;
        ptr_col_d0 : OUT STD_LOGIC_VECTOR (31 downto 0);
        ptr_col_q0 : IN STD_LOGIC_VECTOR (31 downto 0);
        dst_buff : IN STD_LOGIC_VECTOR (63 downto 0);
        src_buff : IN STD_LOGIC_VECTOR (63 downto 0);
        ptr_col2_address0 : OUT STD_LOGIC_VECTOR (2 downto 0);
        ptr_col2_ce0 : OUT STD_LOGIC;
        ptr_col2_we0 : OUT STD_LOGIC;
        ptr_col2_d0 : OUT STD_LOGIC_VECTOR (31 downto 0);
        ptr_col2_q0 : IN STD_LOGIC_VECTOR (31 downto 0);
        ptr_col2_base_address0 : OUT STD_LOGIC_VECTOR (2 downto 0);
        ptr_col2_base_ce0 : OUT STD_LOGIC;
        ptr_col2_base_q0 : IN STD_LOGIC_VECTOR (31 downto 0) );
    end component;


    component dut_mul_32s_34ns_65_5_1 IS
    generic (
        ID : INTEGER;
        NUM_STAGE : INTEGER;
        din0_WIDTH : INTEGER;
        din1_WIDTH : INTEGER;
        dout_WIDTH : INTEGER );
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        din0 : IN STD_LOGIC_VECTOR (31 downto 0);
        din1 : IN STD_LOGIC_VECTOR (33 downto 0);
        ce : IN STD_LOGIC;
        dout : OUT STD_LOGIC_VECTOR (64 downto 0) );
    end component;


    component dut_ptr_col_RAM_AUTO_1R1W IS
    generic (
        DataWidth : INTEGER;
        AddressRange : INTEGER;
        AddressWidth : INTEGER );
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        address0 : IN STD_LOGIC_VECTOR (2 downto 0);
        ce0 : IN STD_LOGIC;
        we0 : IN STD_LOGIC;
        d0 : IN STD_LOGIC_VECTOR (31 downto 0);
        q0 : OUT STD_LOGIC_VECTOR (31 downto 0);
        address1 : IN STD_LOGIC_VECTOR (2 downto 0);
        ce1 : IN STD_LOGIC;
        we1 : IN STD_LOGIC;
        d1 : IN STD_LOGIC_VECTOR (31 downto 0);
        q1 : OUT STD_LOGIC_VECTOR (31 downto 0) );
    end component;


    component dut_ptr_col2_RAM_AUTO_1R1W IS
    generic (
        DataWidth : INTEGER;
        AddressRange : INTEGER;
        AddressWidth : INTEGER );
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        address0 : IN STD_LOGIC_VECTOR (2 downto 0);
        ce0 : IN STD_LOGIC;
        we0 : IN STD_LOGIC;
        d0 : IN STD_LOGIC_VECTOR (31 downto 0);
        q0 : OUT STD_LOGIC_VECTOR (31 downto 0) );
    end component;


    component dut_control_s_axi IS
    generic (
        C_S_AXI_ADDR_WIDTH : INTEGER;
        C_S_AXI_DATA_WIDTH : INTEGER );
    port (
        AWVALID : IN STD_LOGIC;
        AWREADY : OUT STD_LOGIC;
        AWADDR : IN STD_LOGIC_VECTOR (C_S_AXI_ADDR_WIDTH-1 downto 0);
        WVALID : IN STD_LOGIC;
        WREADY : OUT STD_LOGIC;
        WDATA : IN STD_LOGIC_VECTOR (C_S_AXI_DATA_WIDTH-1 downto 0);
        WSTRB : IN STD_LOGIC_VECTOR (C_S_AXI_DATA_WIDTH/8-1 downto 0);
        ARVALID : IN STD_LOGIC;
        ARREADY : OUT STD_LOGIC;
        ARADDR : IN STD_LOGIC_VECTOR (C_S_AXI_ADDR_WIDTH-1 downto 0);
        RVALID : OUT STD_LOGIC;
        RREADY : IN STD_LOGIC;
        RDATA : OUT STD_LOGIC_VECTOR (C_S_AXI_DATA_WIDTH-1 downto 0);
        RRESP : OUT STD_LOGIC_VECTOR (1 downto 0);
        BVALID : OUT STD_LOGIC;
        BREADY : IN STD_LOGIC;
        BRESP : OUT STD_LOGIC_VECTOR (1 downto 0);
        ACLK : IN STD_LOGIC;
        ARESET : IN STD_LOGIC;
        ACLK_EN : IN STD_LOGIC;
        src_buff : OUT STD_LOGIC_VECTOR (63 downto 0);
        src_sz : OUT STD_LOGIC_VECTOR (31 downto 0);
        dst_buff : OUT STD_LOGIC_VECTOR (63 downto 0) );
    end component;


    component dut_gmem_m_axi IS
    generic (
        CONSERVATIVE : INTEGER;
        USER_MAXREQS : INTEGER;
        NUM_READ_OUTSTANDING : INTEGER;
        NUM_WRITE_OUTSTANDING : INTEGER;
        MAX_READ_BURST_LENGTH : INTEGER;
        MAX_WRITE_BURST_LENGTH : INTEGER;
        USER_RFIFONUM_WIDTH : INTEGER;
        C_M_AXI_ID_WIDTH : INTEGER;
        C_M_AXI_ADDR_WIDTH : INTEGER;
        C_M_AXI_DATA_WIDTH : INTEGER;
        C_M_AXI_AWUSER_WIDTH : INTEGER;
        C_M_AXI_ARUSER_WIDTH : INTEGER;
        C_M_AXI_WUSER_WIDTH : INTEGER;
        C_M_AXI_RUSER_WIDTH : INTEGER;
        C_M_AXI_BUSER_WIDTH : INTEGER;
        C_USER_VALUE : INTEGER;
        C_PROT_VALUE : INTEGER;
        C_CACHE_VALUE : INTEGER;
        USER_DW : INTEGER;
        USER_AW : INTEGER );
    port (
        AWVALID : OUT STD_LOGIC;
        AWREADY : IN STD_LOGIC;
        AWADDR : OUT STD_LOGIC_VECTOR (C_M_AXI_ADDR_WIDTH-1 downto 0);
        AWID : OUT STD_LOGIC_VECTOR (C_M_AXI_ID_WIDTH-1 downto 0);
        AWLEN : OUT STD_LOGIC_VECTOR (7 downto 0);
        AWSIZE : OUT STD_LOGIC_VECTOR (2 downto 0);
        AWBURST : OUT STD_LOGIC_VECTOR (1 downto 0);
        AWLOCK : OUT STD_LOGIC_VECTOR (1 downto 0);
        AWCACHE : OUT STD_LOGIC_VECTOR (3 downto 0);
        AWPROT : OUT STD_LOGIC_VECTOR (2 downto 0);
        AWQOS : OUT STD_LOGIC_VECTOR (3 downto 0);
        AWREGION : OUT STD_LOGIC_VECTOR (3 downto 0);
        AWUSER : OUT STD_LOGIC_VECTOR (C_M_AXI_AWUSER_WIDTH-1 downto 0);
        WVALID : OUT STD_LOGIC;
        WREADY : IN STD_LOGIC;
        WDATA : OUT STD_LOGIC_VECTOR (C_M_AXI_DATA_WIDTH-1 downto 0);
        WSTRB : OUT STD_LOGIC_VECTOR (C_M_AXI_DATA_WIDTH/8-1 downto 0);
        WLAST : OUT STD_LOGIC;
        WID : OUT STD_LOGIC_VECTOR (C_M_AXI_ID_WIDTH-1 downto 0);
        WUSER : OUT STD_LOGIC_VECTOR (C_M_AXI_WUSER_WIDTH-1 downto 0);
        ARVALID : OUT STD_LOGIC;
        ARREADY : IN STD_LOGIC;
        ARADDR : OUT STD_LOGIC_VECTOR (C_M_AXI_ADDR_WIDTH-1 downto 0);
        ARID : OUT STD_LOGIC_VECTOR (C_M_AXI_ID_WIDTH-1 downto 0);
        ARLEN : OUT STD_LOGIC_VECTOR (7 downto 0);
        ARSIZE : OUT STD_LOGIC_VECTOR (2 downto 0);
        ARBURST : OUT STD_LOGIC_VECTOR (1 downto 0);
        ARLOCK : OUT STD_LOGIC_VECTOR (1 downto 0);
        ARCACHE : OUT STD_LOGIC_VECTOR (3 downto 0);
        ARPROT : OUT STD_LOGIC_VECTOR (2 downto 0);
        ARQOS : OUT STD_LOGIC_VECTOR (3 downto 0);
        ARREGION : OUT STD_LOGIC_VECTOR (3 downto 0);
        ARUSER : OUT STD_LOGIC_VECTOR (C_M_AXI_ARUSER_WIDTH-1 downto 0);
        RVALID : IN STD_LOGIC;
        RREADY : OUT STD_LOGIC;
        RDATA : IN STD_LOGIC_VECTOR (C_M_AXI_DATA_WIDTH-1 downto 0);
        RLAST : IN STD_LOGIC;
        RID : IN STD_LOGIC_VECTOR (C_M_AXI_ID_WIDTH-1 downto 0);
        RUSER : IN STD_LOGIC_VECTOR (C_M_AXI_RUSER_WIDTH-1 downto 0);
        RRESP : IN STD_LOGIC_VECTOR (1 downto 0);
        BVALID : IN STD_LOGIC;
        BREADY : OUT STD_LOGIC;
        BRESP : IN STD_LOGIC_VECTOR (1 downto 0);
        BID : IN STD_LOGIC_VECTOR (C_M_AXI_ID_WIDTH-1 downto 0);
        BUSER : IN STD_LOGIC_VECTOR (C_M_AXI_BUSER_WIDTH-1 downto 0);
        ACLK : IN STD_LOGIC;
        ARESET : IN STD_LOGIC;
        ACLK_EN : IN STD_LOGIC;
        I_ARVALID : IN STD_LOGIC;
        I_ARREADY : OUT STD_LOGIC;
        I_ARADDR : IN STD_LOGIC_VECTOR (63 downto 0);
        I_ARLEN : IN STD_LOGIC_VECTOR (31 downto 0);
        I_RVALID : OUT STD_LOGIC;
        I_RREADY : IN STD_LOGIC;
        I_RDATA : OUT STD_LOGIC_VECTOR (7 downto 0);
        I_RFIFONUM : OUT STD_LOGIC_VECTOR (10 downto 0);
        I_AWVALID : IN STD_LOGIC;
        I_AWREADY : OUT STD_LOGIC;
        I_AWADDR : IN STD_LOGIC_VECTOR (63 downto 0);
        I_AWLEN : IN STD_LOGIC_VECTOR (31 downto 0);
        I_WVALID : IN STD_LOGIC;
        I_WREADY : OUT STD_LOGIC;
        I_WDATA : IN STD_LOGIC_VECTOR (7 downto 0);
        I_WSTRB : IN STD_LOGIC_VECTOR (0 downto 0);
        I_BVALID : OUT STD_LOGIC;
        I_BREADY : IN STD_LOGIC );
    end component;



begin
    ptr_col_U : component dut_ptr_col_RAM_AUTO_1R1W
    generic map (
        DataWidth => 32,
        AddressRange => 7,
        AddressWidth => 3)
    port map (
        clk => ap_clk,
        reset => ap_rst_n_inv,
        address0 => ptr_col_address0,
        ce0 => ptr_col_ce0,
        we0 => ptr_col_we0,
        d0 => ptr_col_d0,
        q0 => ptr_col_q0,
        address1 => grp_dut_Pipeline_VITIS_LOOP_38_1_fu_148_ptr_col_address1,
        ce1 => ptr_col_ce1,
        we1 => ptr_col_we1,
        d1 => grp_dut_Pipeline_VITIS_LOOP_38_1_fu_148_ptr_col_d1,
        q1 => ptr_col_q1);

    ptr_col2_U : component dut_ptr_col2_RAM_AUTO_1R1W
    generic map (
        DataWidth => 32,
        AddressRange => 7,
        AddressWidth => 3)
    port map (
        clk => ap_clk,
        reset => ap_rst_n_inv,
        address0 => ptr_col2_address0,
        ce0 => ptr_col2_ce0,
        we0 => ptr_col2_we0,
        d0 => ptr_col2_d0,
        q0 => ptr_col2_q0);

    ptr_col2_base_U : component dut_ptr_col2_RAM_AUTO_1R1W
    generic map (
        DataWidth => 32,
        AddressRange => 7,
        AddressWidth => 3)
    port map (
        clk => ap_clk,
        reset => ap_rst_n_inv,
        address0 => ptr_col2_base_address0,
        ce0 => ptr_col2_base_ce0,
        we0 => ptr_col2_base_we0,
        d0 => ptr_col2_base_d0,
        q0 => ptr_col2_base_q0);

    grp_dut_Pipeline_1_fu_130 : component dut_dut_Pipeline_1
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst_n_inv,
        ap_start => grp_dut_Pipeline_1_fu_130_ap_start,
        ap_done => grp_dut_Pipeline_1_fu_130_ap_done,
        ap_idle => grp_dut_Pipeline_1_fu_130_ap_idle,
        ap_ready => grp_dut_Pipeline_1_fu_130_ap_ready,
        ptr_col_address0 => grp_dut_Pipeline_1_fu_130_ptr_col_address0,
        ptr_col_ce0 => grp_dut_Pipeline_1_fu_130_ptr_col_ce0,
        ptr_col_we0 => grp_dut_Pipeline_1_fu_130_ptr_col_we0,
        ptr_col_d0 => grp_dut_Pipeline_1_fu_130_ptr_col_d0);

    grp_dut_Pipeline_2_fu_136 : component dut_dut_Pipeline_2
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst_n_inv,
        ap_start => grp_dut_Pipeline_2_fu_136_ap_start,
        ap_done => grp_dut_Pipeline_2_fu_136_ap_done,
        ap_idle => grp_dut_Pipeline_2_fu_136_ap_idle,
        ap_ready => grp_dut_Pipeline_2_fu_136_ap_ready,
        ptr_col2_address0 => grp_dut_Pipeline_2_fu_136_ptr_col2_address0,
        ptr_col2_ce0 => grp_dut_Pipeline_2_fu_136_ptr_col2_ce0,
        ptr_col2_we0 => grp_dut_Pipeline_2_fu_136_ptr_col2_we0,
        ptr_col2_d0 => grp_dut_Pipeline_2_fu_136_ptr_col2_d0);

    grp_dut_Pipeline_3_fu_142 : component dut_dut_Pipeline_3
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst_n_inv,
        ap_start => grp_dut_Pipeline_3_fu_142_ap_start,
        ap_done => grp_dut_Pipeline_3_fu_142_ap_done,
        ap_idle => grp_dut_Pipeline_3_fu_142_ap_idle,
        ap_ready => grp_dut_Pipeline_3_fu_142_ap_ready,
        ptr_col2_base_address0 => grp_dut_Pipeline_3_fu_142_ptr_col2_base_address0,
        ptr_col2_base_ce0 => grp_dut_Pipeline_3_fu_142_ptr_col2_base_ce0,
        ptr_col2_base_we0 => grp_dut_Pipeline_3_fu_142_ptr_col2_base_we0,
        ptr_col2_base_d0 => grp_dut_Pipeline_3_fu_142_ptr_col2_base_d0);

    grp_dut_Pipeline_VITIS_LOOP_38_1_fu_148 : component dut_dut_Pipeline_VITIS_LOOP_38_1
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst_n_inv,
        ap_start => grp_dut_Pipeline_VITIS_LOOP_38_1_fu_148_ap_start,
        ap_done => grp_dut_Pipeline_VITIS_LOOP_38_1_fu_148_ap_done,
        ap_idle => grp_dut_Pipeline_VITIS_LOOP_38_1_fu_148_ap_idle,
        ap_ready => grp_dut_Pipeline_VITIS_LOOP_38_1_fu_148_ap_ready,
        m_axi_gmem_AWVALID => grp_dut_Pipeline_VITIS_LOOP_38_1_fu_148_m_axi_gmem_AWVALID,
        m_axi_gmem_AWREADY => gmem_AWREADY,
        m_axi_gmem_AWADDR => grp_dut_Pipeline_VITIS_LOOP_38_1_fu_148_m_axi_gmem_AWADDR,
        m_axi_gmem_AWID => grp_dut_Pipeline_VITIS_LOOP_38_1_fu_148_m_axi_gmem_AWID,
        m_axi_gmem_AWLEN => grp_dut_Pipeline_VITIS_LOOP_38_1_fu_148_m_axi_gmem_AWLEN,
        m_axi_gmem_AWSIZE => grp_dut_Pipeline_VITIS_LOOP_38_1_fu_148_m_axi_gmem_AWSIZE,
        m_axi_gmem_AWBURST => grp_dut_Pipeline_VITIS_LOOP_38_1_fu_148_m_axi_gmem_AWBURST,
        m_axi_gmem_AWLOCK => grp_dut_Pipeline_VITIS_LOOP_38_1_fu_148_m_axi_gmem_AWLOCK,
        m_axi_gmem_AWCACHE => grp_dut_Pipeline_VITIS_LOOP_38_1_fu_148_m_axi_gmem_AWCACHE,
        m_axi_gmem_AWPROT => grp_dut_Pipeline_VITIS_LOOP_38_1_fu_148_m_axi_gmem_AWPROT,
        m_axi_gmem_AWQOS => grp_dut_Pipeline_VITIS_LOOP_38_1_fu_148_m_axi_gmem_AWQOS,
        m_axi_gmem_AWREGION => grp_dut_Pipeline_VITIS_LOOP_38_1_fu_148_m_axi_gmem_AWREGION,
        m_axi_gmem_AWUSER => grp_dut_Pipeline_VITIS_LOOP_38_1_fu_148_m_axi_gmem_AWUSER,
        m_axi_gmem_WVALID => grp_dut_Pipeline_VITIS_LOOP_38_1_fu_148_m_axi_gmem_WVALID,
        m_axi_gmem_WREADY => gmem_WREADY,
        m_axi_gmem_WDATA => grp_dut_Pipeline_VITIS_LOOP_38_1_fu_148_m_axi_gmem_WDATA,
        m_axi_gmem_WSTRB => grp_dut_Pipeline_VITIS_LOOP_38_1_fu_148_m_axi_gmem_WSTRB,
        m_axi_gmem_WLAST => grp_dut_Pipeline_VITIS_LOOP_38_1_fu_148_m_axi_gmem_WLAST,
        m_axi_gmem_WID => grp_dut_Pipeline_VITIS_LOOP_38_1_fu_148_m_axi_gmem_WID,
        m_axi_gmem_WUSER => grp_dut_Pipeline_VITIS_LOOP_38_1_fu_148_m_axi_gmem_WUSER,
        m_axi_gmem_ARVALID => grp_dut_Pipeline_VITIS_LOOP_38_1_fu_148_m_axi_gmem_ARVALID,
        m_axi_gmem_ARREADY => gmem_ARREADY,
        m_axi_gmem_ARADDR => grp_dut_Pipeline_VITIS_LOOP_38_1_fu_148_m_axi_gmem_ARADDR,
        m_axi_gmem_ARID => grp_dut_Pipeline_VITIS_LOOP_38_1_fu_148_m_axi_gmem_ARID,
        m_axi_gmem_ARLEN => grp_dut_Pipeline_VITIS_LOOP_38_1_fu_148_m_axi_gmem_ARLEN,
        m_axi_gmem_ARSIZE => grp_dut_Pipeline_VITIS_LOOP_38_1_fu_148_m_axi_gmem_ARSIZE,
        m_axi_gmem_ARBURST => grp_dut_Pipeline_VITIS_LOOP_38_1_fu_148_m_axi_gmem_ARBURST,
        m_axi_gmem_ARLOCK => grp_dut_Pipeline_VITIS_LOOP_38_1_fu_148_m_axi_gmem_ARLOCK,
        m_axi_gmem_ARCACHE => grp_dut_Pipeline_VITIS_LOOP_38_1_fu_148_m_axi_gmem_ARCACHE,
        m_axi_gmem_ARPROT => grp_dut_Pipeline_VITIS_LOOP_38_1_fu_148_m_axi_gmem_ARPROT,
        m_axi_gmem_ARQOS => grp_dut_Pipeline_VITIS_LOOP_38_1_fu_148_m_axi_gmem_ARQOS,
        m_axi_gmem_ARREGION => grp_dut_Pipeline_VITIS_LOOP_38_1_fu_148_m_axi_gmem_ARREGION,
        m_axi_gmem_ARUSER => grp_dut_Pipeline_VITIS_LOOP_38_1_fu_148_m_axi_gmem_ARUSER,
        m_axi_gmem_RVALID => gmem_RVALID,
        m_axi_gmem_RREADY => grp_dut_Pipeline_VITIS_LOOP_38_1_fu_148_m_axi_gmem_RREADY,
        m_axi_gmem_RDATA => gmem_RDATA,
        m_axi_gmem_RLAST => ap_const_logic_0,
        m_axi_gmem_RID => ap_const_lv1_0,
        m_axi_gmem_RFIFONUM => gmem_RFIFONUM,
        m_axi_gmem_RUSER => ap_const_lv1_0,
        m_axi_gmem_RRESP => ap_const_lv2_0,
        m_axi_gmem_BVALID => gmem_BVALID,
        m_axi_gmem_BREADY => grp_dut_Pipeline_VITIS_LOOP_38_1_fu_148_m_axi_gmem_BREADY,
        m_axi_gmem_BRESP => ap_const_lv2_0,
        m_axi_gmem_BID => ap_const_lv1_0,
        m_axi_gmem_BUSER => ap_const_lv1_0,
        src_buff => src_buff_read_reg_260,
        add_ln41 => add_ln41_reg_266,
        ptr_col_address0 => grp_dut_Pipeline_VITIS_LOOP_38_1_fu_148_ptr_col_address0,
        ptr_col_ce0 => grp_dut_Pipeline_VITIS_LOOP_38_1_fu_148_ptr_col_ce0,
        ptr_col_we0 => grp_dut_Pipeline_VITIS_LOOP_38_1_fu_148_ptr_col_we0,
        ptr_col_d0 => grp_dut_Pipeline_VITIS_LOOP_38_1_fu_148_ptr_col_d0,
        ptr_col_q0 => ptr_col_q0,
        ptr_col_address1 => grp_dut_Pipeline_VITIS_LOOP_38_1_fu_148_ptr_col_address1,
        ptr_col_ce1 => grp_dut_Pipeline_VITIS_LOOP_38_1_fu_148_ptr_col_ce1,
        ptr_col_we1 => grp_dut_Pipeline_VITIS_LOOP_38_1_fu_148_ptr_col_we1,
        ptr_col_d1 => grp_dut_Pipeline_VITIS_LOOP_38_1_fu_148_ptr_col_d1,
        ptr_col_q1 => ptr_col_q1,
        ptr_col2_address0 => grp_dut_Pipeline_VITIS_LOOP_38_1_fu_148_ptr_col2_address0,
        ptr_col2_ce0 => grp_dut_Pipeline_VITIS_LOOP_38_1_fu_148_ptr_col2_ce0,
        ptr_col2_we0 => grp_dut_Pipeline_VITIS_LOOP_38_1_fu_148_ptr_col2_we0,
        ptr_col2_d0 => grp_dut_Pipeline_VITIS_LOOP_38_1_fu_148_ptr_col2_d0,
        ptr_col2_base_address0 => grp_dut_Pipeline_VITIS_LOOP_38_1_fu_148_ptr_col2_base_address0,
        ptr_col2_base_ce0 => grp_dut_Pipeline_VITIS_LOOP_38_1_fu_148_ptr_col2_base_ce0,
        ptr_col2_base_we0 => grp_dut_Pipeline_VITIS_LOOP_38_1_fu_148_ptr_col2_base_we0,
        ptr_col2_base_d0 => grp_dut_Pipeline_VITIS_LOOP_38_1_fu_148_ptr_col2_base_d0,
        dst_buff => dst_buff_read_reg_254);

    grp_dut_Pipeline_VITIS_LOOP_73_2_fu_160 : component dut_dut_Pipeline_VITIS_LOOP_73_2
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst_n_inv,
        ap_start => grp_dut_Pipeline_VITIS_LOOP_73_2_fu_160_ap_start,
        ap_done => grp_dut_Pipeline_VITIS_LOOP_73_2_fu_160_ap_done,
        ap_idle => grp_dut_Pipeline_VITIS_LOOP_73_2_fu_160_ap_idle,
        ap_ready => grp_dut_Pipeline_VITIS_LOOP_73_2_fu_160_ap_ready,
        m_axi_gmem_AWVALID => grp_dut_Pipeline_VITIS_LOOP_73_2_fu_160_m_axi_gmem_AWVALID,
        m_axi_gmem_AWREADY => gmem_AWREADY,
        m_axi_gmem_AWADDR => grp_dut_Pipeline_VITIS_LOOP_73_2_fu_160_m_axi_gmem_AWADDR,
        m_axi_gmem_AWID => grp_dut_Pipeline_VITIS_LOOP_73_2_fu_160_m_axi_gmem_AWID,
        m_axi_gmem_AWLEN => grp_dut_Pipeline_VITIS_LOOP_73_2_fu_160_m_axi_gmem_AWLEN,
        m_axi_gmem_AWSIZE => grp_dut_Pipeline_VITIS_LOOP_73_2_fu_160_m_axi_gmem_AWSIZE,
        m_axi_gmem_AWBURST => grp_dut_Pipeline_VITIS_LOOP_73_2_fu_160_m_axi_gmem_AWBURST,
        m_axi_gmem_AWLOCK => grp_dut_Pipeline_VITIS_LOOP_73_2_fu_160_m_axi_gmem_AWLOCK,
        m_axi_gmem_AWCACHE => grp_dut_Pipeline_VITIS_LOOP_73_2_fu_160_m_axi_gmem_AWCACHE,
        m_axi_gmem_AWPROT => grp_dut_Pipeline_VITIS_LOOP_73_2_fu_160_m_axi_gmem_AWPROT,
        m_axi_gmem_AWQOS => grp_dut_Pipeline_VITIS_LOOP_73_2_fu_160_m_axi_gmem_AWQOS,
        m_axi_gmem_AWREGION => grp_dut_Pipeline_VITIS_LOOP_73_2_fu_160_m_axi_gmem_AWREGION,
        m_axi_gmem_AWUSER => grp_dut_Pipeline_VITIS_LOOP_73_2_fu_160_m_axi_gmem_AWUSER,
        m_axi_gmem_WVALID => grp_dut_Pipeline_VITIS_LOOP_73_2_fu_160_m_axi_gmem_WVALID,
        m_axi_gmem_WREADY => gmem_WREADY,
        m_axi_gmem_WDATA => grp_dut_Pipeline_VITIS_LOOP_73_2_fu_160_m_axi_gmem_WDATA,
        m_axi_gmem_WSTRB => grp_dut_Pipeline_VITIS_LOOP_73_2_fu_160_m_axi_gmem_WSTRB,
        m_axi_gmem_WLAST => grp_dut_Pipeline_VITIS_LOOP_73_2_fu_160_m_axi_gmem_WLAST,
        m_axi_gmem_WID => grp_dut_Pipeline_VITIS_LOOP_73_2_fu_160_m_axi_gmem_WID,
        m_axi_gmem_WUSER => grp_dut_Pipeline_VITIS_LOOP_73_2_fu_160_m_axi_gmem_WUSER,
        m_axi_gmem_ARVALID => grp_dut_Pipeline_VITIS_LOOP_73_2_fu_160_m_axi_gmem_ARVALID,
        m_axi_gmem_ARREADY => gmem_ARREADY,
        m_axi_gmem_ARADDR => grp_dut_Pipeline_VITIS_LOOP_73_2_fu_160_m_axi_gmem_ARADDR,
        m_axi_gmem_ARID => grp_dut_Pipeline_VITIS_LOOP_73_2_fu_160_m_axi_gmem_ARID,
        m_axi_gmem_ARLEN => grp_dut_Pipeline_VITIS_LOOP_73_2_fu_160_m_axi_gmem_ARLEN,
        m_axi_gmem_ARSIZE => grp_dut_Pipeline_VITIS_LOOP_73_2_fu_160_m_axi_gmem_ARSIZE,
        m_axi_gmem_ARBURST => grp_dut_Pipeline_VITIS_LOOP_73_2_fu_160_m_axi_gmem_ARBURST,
        m_axi_gmem_ARLOCK => grp_dut_Pipeline_VITIS_LOOP_73_2_fu_160_m_axi_gmem_ARLOCK,
        m_axi_gmem_ARCACHE => grp_dut_Pipeline_VITIS_LOOP_73_2_fu_160_m_axi_gmem_ARCACHE,
        m_axi_gmem_ARPROT => grp_dut_Pipeline_VITIS_LOOP_73_2_fu_160_m_axi_gmem_ARPROT,
        m_axi_gmem_ARQOS => grp_dut_Pipeline_VITIS_LOOP_73_2_fu_160_m_axi_gmem_ARQOS,
        m_axi_gmem_ARREGION => grp_dut_Pipeline_VITIS_LOOP_73_2_fu_160_m_axi_gmem_ARREGION,
        m_axi_gmem_ARUSER => grp_dut_Pipeline_VITIS_LOOP_73_2_fu_160_m_axi_gmem_ARUSER,
        m_axi_gmem_RVALID => gmem_RVALID,
        m_axi_gmem_RREADY => grp_dut_Pipeline_VITIS_LOOP_73_2_fu_160_m_axi_gmem_RREADY,
        m_axi_gmem_RDATA => gmem_RDATA,
        m_axi_gmem_RLAST => ap_const_logic_0,
        m_axi_gmem_RID => ap_const_lv1_0,
        m_axi_gmem_RFIFONUM => gmem_RFIFONUM,
        m_axi_gmem_RUSER => ap_const_lv1_0,
        m_axi_gmem_RRESP => ap_const_lv2_0,
        m_axi_gmem_BVALID => gmem_BVALID,
        m_axi_gmem_BREADY => grp_dut_Pipeline_VITIS_LOOP_73_2_fu_160_m_axi_gmem_BREADY,
        m_axi_gmem_BRESP => ap_const_lv2_0,
        m_axi_gmem_BID => ap_const_lv1_0,
        m_axi_gmem_BUSER => ap_const_lv1_0,
        next_col_idx_V => next_col_idx_V_reg_310,
        sub => sub_reg_305,
        ptr_col_address0 => grp_dut_Pipeline_VITIS_LOOP_73_2_fu_160_ptr_col_address0,
        ptr_col_ce0 => grp_dut_Pipeline_VITIS_LOOP_73_2_fu_160_ptr_col_ce0,
        ptr_col_we0 => grp_dut_Pipeline_VITIS_LOOP_73_2_fu_160_ptr_col_we0,
        ptr_col_d0 => grp_dut_Pipeline_VITIS_LOOP_73_2_fu_160_ptr_col_d0,
        ptr_col_q0 => ptr_col_q0,
        dst_buff => dst_buff_read_reg_254,
        src_buff => src_buff_read_reg_260,
        ptr_col2_address0 => grp_dut_Pipeline_VITIS_LOOP_73_2_fu_160_ptr_col2_address0,
        ptr_col2_ce0 => grp_dut_Pipeline_VITIS_LOOP_73_2_fu_160_ptr_col2_ce0,
        ptr_col2_we0 => grp_dut_Pipeline_VITIS_LOOP_73_2_fu_160_ptr_col2_we0,
        ptr_col2_d0 => grp_dut_Pipeline_VITIS_LOOP_73_2_fu_160_ptr_col2_d0,
        ptr_col2_q0 => ptr_col2_q0,
        ptr_col2_base_address0 => grp_dut_Pipeline_VITIS_LOOP_73_2_fu_160_ptr_col2_base_address0,
        ptr_col2_base_ce0 => grp_dut_Pipeline_VITIS_LOOP_73_2_fu_160_ptr_col2_base_ce0,
        ptr_col2_base_q0 => ptr_col2_base_q0);

    control_s_axi_U : component dut_control_s_axi
    generic map (
        C_S_AXI_ADDR_WIDTH => C_S_AXI_CONTROL_ADDR_WIDTH,
        C_S_AXI_DATA_WIDTH => C_S_AXI_CONTROL_DATA_WIDTH)
    port map (
        AWVALID => s_axi_control_AWVALID,
        AWREADY => s_axi_control_AWREADY,
        AWADDR => s_axi_control_AWADDR,
        WVALID => s_axi_control_WVALID,
        WREADY => s_axi_control_WREADY,
        WDATA => s_axi_control_WDATA,
        WSTRB => s_axi_control_WSTRB,
        ARVALID => s_axi_control_ARVALID,
        ARREADY => s_axi_control_ARREADY,
        ARADDR => s_axi_control_ARADDR,
        RVALID => s_axi_control_RVALID,
        RREADY => s_axi_control_RREADY,
        RDATA => s_axi_control_RDATA,
        RRESP => s_axi_control_RRESP,
        BVALID => s_axi_control_BVALID,
        BREADY => s_axi_control_BREADY,
        BRESP => s_axi_control_BRESP,
        ACLK => ap_clk,
        ARESET => ap_rst_n_inv,
        ACLK_EN => ap_const_logic_1,
        src_buff => src_buff,
        src_sz => src_sz,
        dst_buff => dst_buff);

    gmem_m_axi_U : component dut_gmem_m_axi
    generic map (
        CONSERVATIVE => 1,
        USER_MAXREQS => 5,
        NUM_READ_OUTSTANDING => 16,
        NUM_WRITE_OUTSTANDING => 16,
        MAX_READ_BURST_LENGTH => 16,
        MAX_WRITE_BURST_LENGTH => 16,
        USER_RFIFONUM_WIDTH => 11,
        C_M_AXI_ID_WIDTH => C_M_AXI_GMEM_ID_WIDTH,
        C_M_AXI_ADDR_WIDTH => C_M_AXI_GMEM_ADDR_WIDTH,
        C_M_AXI_DATA_WIDTH => C_M_AXI_GMEM_DATA_WIDTH,
        C_M_AXI_AWUSER_WIDTH => C_M_AXI_GMEM_AWUSER_WIDTH,
        C_M_AXI_ARUSER_WIDTH => C_M_AXI_GMEM_ARUSER_WIDTH,
        C_M_AXI_WUSER_WIDTH => C_M_AXI_GMEM_WUSER_WIDTH,
        C_M_AXI_RUSER_WIDTH => C_M_AXI_GMEM_RUSER_WIDTH,
        C_M_AXI_BUSER_WIDTH => C_M_AXI_GMEM_BUSER_WIDTH,
        C_USER_VALUE => C_M_AXI_GMEM_USER_VALUE,
        C_PROT_VALUE => C_M_AXI_GMEM_PROT_VALUE,
        C_CACHE_VALUE => C_M_AXI_GMEM_CACHE_VALUE,
        USER_DW => 8,
        USER_AW => 64)
    port map (
        AWVALID => m_axi_gmem_AWVALID,
        AWREADY => m_axi_gmem_AWREADY,
        AWADDR => m_axi_gmem_AWADDR,
        AWID => m_axi_gmem_AWID,
        AWLEN => m_axi_gmem_AWLEN,
        AWSIZE => m_axi_gmem_AWSIZE,
        AWBURST => m_axi_gmem_AWBURST,
        AWLOCK => m_axi_gmem_AWLOCK,
        AWCACHE => m_axi_gmem_AWCACHE,
        AWPROT => m_axi_gmem_AWPROT,
        AWQOS => m_axi_gmem_AWQOS,
        AWREGION => m_axi_gmem_AWREGION,
        AWUSER => m_axi_gmem_AWUSER,
        WVALID => m_axi_gmem_WVALID,
        WREADY => m_axi_gmem_WREADY,
        WDATA => m_axi_gmem_WDATA,
        WSTRB => m_axi_gmem_WSTRB,
        WLAST => m_axi_gmem_WLAST,
        WID => m_axi_gmem_WID,
        WUSER => m_axi_gmem_WUSER,
        ARVALID => m_axi_gmem_ARVALID,
        ARREADY => m_axi_gmem_ARREADY,
        ARADDR => m_axi_gmem_ARADDR,
        ARID => m_axi_gmem_ARID,
        ARLEN => m_axi_gmem_ARLEN,
        ARSIZE => m_axi_gmem_ARSIZE,
        ARBURST => m_axi_gmem_ARBURST,
        ARLOCK => m_axi_gmem_ARLOCK,
        ARCACHE => m_axi_gmem_ARCACHE,
        ARPROT => m_axi_gmem_ARPROT,
        ARQOS => m_axi_gmem_ARQOS,
        ARREGION => m_axi_gmem_ARREGION,
        ARUSER => m_axi_gmem_ARUSER,
        RVALID => m_axi_gmem_RVALID,
        RREADY => m_axi_gmem_RREADY,
        RDATA => m_axi_gmem_RDATA,
        RLAST => m_axi_gmem_RLAST,
        RID => m_axi_gmem_RID,
        RUSER => m_axi_gmem_RUSER,
        RRESP => m_axi_gmem_RRESP,
        BVALID => m_axi_gmem_BVALID,
        BREADY => m_axi_gmem_BREADY,
        BRESP => m_axi_gmem_BRESP,
        BID => m_axi_gmem_BID,
        BUSER => m_axi_gmem_BUSER,
        ACLK => ap_clk,
        ARESET => ap_rst_n_inv,
        ACLK_EN => ap_const_logic_1,
        I_ARVALID => gmem_ARVALID,
        I_ARREADY => gmem_ARREADY,
        I_ARADDR => gmem_ARADDR,
        I_ARLEN => gmem_ARLEN,
        I_RVALID => gmem_RVALID,
        I_RREADY => gmem_RREADY,
        I_RDATA => gmem_RDATA,
        I_RFIFONUM => gmem_RFIFONUM,
        I_AWVALID => gmem_AWVALID,
        I_AWREADY => gmem_AWREADY,
        I_AWADDR => gmem_AWADDR,
        I_AWLEN => gmem_AWLEN,
        I_WVALID => gmem_WVALID,
        I_WREADY => gmem_WREADY,
        I_WDATA => gmem_WDATA,
        I_WSTRB => gmem_WSTRB,
        I_BVALID => gmem_BVALID,
        I_BREADY => gmem_BREADY);

    mul_32s_34ns_65_5_1_U19 : component dut_mul_32s_34ns_65_5_1
    generic map (
        ID => 1,
        NUM_STAGE => 5,
        din0_WIDTH => 32,
        din1_WIDTH => 34,
        dout_WIDTH => 65)
    port map (
        clk => ap_clk,
        reset => ap_rst_n_inv,
        din0 => src_sz,
        din1 => grp_fu_183_p1,
        ce => grp_fu_183_ce,
        dout => grp_fu_183_p2);





    ap_CS_fsm_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst_n_inv = '1') then
                ap_CS_fsm <= ap_ST_fsm_state1;
            else
                ap_CS_fsm <= ap_NS_fsm;
            end if;
        end if;
    end process;


    grp_dut_Pipeline_1_fu_130_ap_start_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst_n_inv = '1') then
                grp_dut_Pipeline_1_fu_130_ap_start_reg <= ap_const_logic_0;
            else
                if (((ap_start = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
                    grp_dut_Pipeline_1_fu_130_ap_start_reg <= ap_const_logic_1;
                elsif ((grp_dut_Pipeline_1_fu_130_ap_ready = ap_const_logic_1)) then 
                    grp_dut_Pipeline_1_fu_130_ap_start_reg <= ap_const_logic_0;
                end if; 
            end if;
        end if;
    end process;


    grp_dut_Pipeline_2_fu_136_ap_start_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst_n_inv = '1') then
                grp_dut_Pipeline_2_fu_136_ap_start_reg <= ap_const_logic_0;
            else
                if (((ap_start = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
                    grp_dut_Pipeline_2_fu_136_ap_start_reg <= ap_const_logic_1;
                elsif ((grp_dut_Pipeline_2_fu_136_ap_ready = ap_const_logic_1)) then 
                    grp_dut_Pipeline_2_fu_136_ap_start_reg <= ap_const_logic_0;
                end if; 
            end if;
        end if;
    end process;


    grp_dut_Pipeline_3_fu_142_ap_start_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst_n_inv = '1') then
                grp_dut_Pipeline_3_fu_142_ap_start_reg <= ap_const_logic_0;
            else
                if (((ap_start = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
                    grp_dut_Pipeline_3_fu_142_ap_start_reg <= ap_const_logic_1;
                elsif ((grp_dut_Pipeline_3_fu_142_ap_ready = ap_const_logic_1)) then 
                    grp_dut_Pipeline_3_fu_142_ap_start_reg <= ap_const_logic_0;
                end if; 
            end if;
        end if;
    end process;


    grp_dut_Pipeline_VITIS_LOOP_38_1_fu_148_ap_start_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst_n_inv = '1') then
                grp_dut_Pipeline_VITIS_LOOP_38_1_fu_148_ap_start_reg <= ap_const_logic_0;
            else
                if ((ap_const_logic_1 = ap_CS_fsm_state3)) then 
                    grp_dut_Pipeline_VITIS_LOOP_38_1_fu_148_ap_start_reg <= ap_const_logic_1;
                elsif ((grp_dut_Pipeline_VITIS_LOOP_38_1_fu_148_ap_ready = ap_const_logic_1)) then 
                    grp_dut_Pipeline_VITIS_LOOP_38_1_fu_148_ap_start_reg <= ap_const_logic_0;
                end if; 
            end if;
        end if;
    end process;


    grp_dut_Pipeline_VITIS_LOOP_73_2_fu_160_ap_start_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst_n_inv = '1') then
                grp_dut_Pipeline_VITIS_LOOP_73_2_fu_160_ap_start_reg <= ap_const_logic_0;
            else
                if (((ap_const_logic_1 = ap_NS_fsm_state13) and (ap_const_logic_1 = ap_CS_fsm_state12))) then 
                    grp_dut_Pipeline_VITIS_LOOP_73_2_fu_160_ap_start_reg <= ap_const_logic_1;
                elsif ((grp_dut_Pipeline_VITIS_LOOP_73_2_fu_160_ap_ready = ap_const_logic_1)) then 
                    grp_dut_Pipeline_VITIS_LOOP_73_2_fu_160_ap_start_reg <= ap_const_logic_0;
                end if; 
            end if;
        end if;
    end process;

    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state2)) then
                add_ln41_reg_266 <= add_ln41_fu_173_p2;
                dst_buff_read_reg_254 <= dst_buff;
                src_buff_read_reg_260 <= src_buff;
                tmp_reg_277 <= tmp_fu_189_p1(31 downto 31);
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state3)) then
                gmem_addr_1_reg_283 <= add_ln41_reg_266;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state6)) then
                mul_reg_289 <= grp_fu_183_p2;
                tmp_4_reg_294 <= grp_fu_183_p2(64 downto 36);
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_CS_fsm_state7) and (tmp_reg_277 = ap_const_lv1_1))) then
                neg_mul_reg_300 <= neg_mul_fu_212_p2;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state12)) then
                next_col_idx_V_reg_310 <= next_col_idx_V_fu_250_p1;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state8)) then
                sub_reg_305 <= sub_fu_244_p2;
            end if;
        end if;
    end process;

    ap_NS_fsm_assign_proc : process (ap_start, ap_CS_fsm, ap_CS_fsm_state1, ap_CS_fsm_state5, ap_CS_fsm_state12, ap_CS_fsm_state2, grp_dut_Pipeline_VITIS_LOOP_38_1_fu_148_ap_done, grp_dut_Pipeline_VITIS_LOOP_73_2_fu_160_ap_done, gmem_ARREADY, gmem_RVALID, ap_CS_fsm_state4, ap_CS_fsm_state14, ap_block_state2_on_subcall_done)
    begin
        case ap_CS_fsm is
            when ap_ST_fsm_state1 => 
                if (((ap_start = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state1))) then
                    ap_NS_fsm <= ap_ST_fsm_state2;
                else
                    ap_NS_fsm <= ap_ST_fsm_state1;
                end if;
            when ap_ST_fsm_state2 => 
                if (((ap_const_boolean_0 = ap_block_state2_on_subcall_done) and (ap_const_logic_1 = ap_CS_fsm_state2))) then
                    ap_NS_fsm <= ap_ST_fsm_state3;
                else
                    ap_NS_fsm <= ap_ST_fsm_state2;
                end if;
            when ap_ST_fsm_state3 => 
                ap_NS_fsm <= ap_ST_fsm_state4;
            when ap_ST_fsm_state4 => 
                if (((grp_dut_Pipeline_VITIS_LOOP_38_1_fu_148_ap_done = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state4))) then
                    ap_NS_fsm <= ap_ST_fsm_state5;
                else
                    ap_NS_fsm <= ap_ST_fsm_state4;
                end if;
            when ap_ST_fsm_state5 => 
                if (((gmem_ARREADY = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state5))) then
                    ap_NS_fsm <= ap_ST_fsm_state6;
                else
                    ap_NS_fsm <= ap_ST_fsm_state5;
                end if;
            when ap_ST_fsm_state6 => 
                ap_NS_fsm <= ap_ST_fsm_state7;
            when ap_ST_fsm_state7 => 
                ap_NS_fsm <= ap_ST_fsm_state8;
            when ap_ST_fsm_state8 => 
                ap_NS_fsm <= ap_ST_fsm_state9;
            when ap_ST_fsm_state9 => 
                ap_NS_fsm <= ap_ST_fsm_state10;
            when ap_ST_fsm_state10 => 
                ap_NS_fsm <= ap_ST_fsm_state11;
            when ap_ST_fsm_state11 => 
                ap_NS_fsm <= ap_ST_fsm_state12;
            when ap_ST_fsm_state12 => 
                if (((gmem_RVALID = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state12))) then
                    ap_NS_fsm <= ap_ST_fsm_state13;
                else
                    ap_NS_fsm <= ap_ST_fsm_state12;
                end if;
            when ap_ST_fsm_state13 => 
                ap_NS_fsm <= ap_ST_fsm_state14;
            when ap_ST_fsm_state14 => 
                if (((grp_dut_Pipeline_VITIS_LOOP_73_2_fu_160_ap_done = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state14))) then
                    ap_NS_fsm <= ap_ST_fsm_state1;
                else
                    ap_NS_fsm <= ap_ST_fsm_state14;
                end if;
            when others =>  
                ap_NS_fsm <= "XXXXXXXXXXXXXX";
        end case;
    end process;
    add_ln41_fu_173_p2 <= std_logic_vector(unsigned(src_buff) + unsigned(ap_const_lv64_2));
    ap_CS_fsm_state1 <= ap_CS_fsm(0);
    ap_CS_fsm_state12 <= ap_CS_fsm(11);
    ap_CS_fsm_state13 <= ap_CS_fsm(12);
    ap_CS_fsm_state14 <= ap_CS_fsm(13);
    ap_CS_fsm_state2 <= ap_CS_fsm(1);
    ap_CS_fsm_state3 <= ap_CS_fsm(2);
    ap_CS_fsm_state4 <= ap_CS_fsm(3);
    ap_CS_fsm_state5 <= ap_CS_fsm(4);
    ap_CS_fsm_state6 <= ap_CS_fsm(5);
    ap_CS_fsm_state7 <= ap_CS_fsm(6);
    ap_CS_fsm_state8 <= ap_CS_fsm(7);
    ap_NS_fsm_state13 <= ap_NS_fsm(12);
    ap_ST_fsm_state10_blk <= ap_const_logic_0;
    ap_ST_fsm_state11_blk <= ap_const_logic_0;

    ap_ST_fsm_state12_blk_assign_proc : process(gmem_RVALID)
    begin
        if ((gmem_RVALID = ap_const_logic_0)) then 
            ap_ST_fsm_state12_blk <= ap_const_logic_1;
        else 
            ap_ST_fsm_state12_blk <= ap_const_logic_0;
        end if; 
    end process;

    ap_ST_fsm_state13_blk <= ap_const_logic_0;

    ap_ST_fsm_state14_blk_assign_proc : process(grp_dut_Pipeline_VITIS_LOOP_73_2_fu_160_ap_done)
    begin
        if ((grp_dut_Pipeline_VITIS_LOOP_73_2_fu_160_ap_done = ap_const_logic_0)) then 
            ap_ST_fsm_state14_blk <= ap_const_logic_1;
        else 
            ap_ST_fsm_state14_blk <= ap_const_logic_0;
        end if; 
    end process;


    ap_ST_fsm_state1_blk_assign_proc : process(ap_start)
    begin
        if ((ap_start = ap_const_logic_0)) then 
            ap_ST_fsm_state1_blk <= ap_const_logic_1;
        else 
            ap_ST_fsm_state1_blk <= ap_const_logic_0;
        end if; 
    end process;


    ap_ST_fsm_state2_blk_assign_proc : process(ap_block_state2_on_subcall_done)
    begin
        if ((ap_const_boolean_1 = ap_block_state2_on_subcall_done)) then 
            ap_ST_fsm_state2_blk <= ap_const_logic_1;
        else 
            ap_ST_fsm_state2_blk <= ap_const_logic_0;
        end if; 
    end process;

    ap_ST_fsm_state3_blk <= ap_const_logic_0;

    ap_ST_fsm_state4_blk_assign_proc : process(grp_dut_Pipeline_VITIS_LOOP_38_1_fu_148_ap_done)
    begin
        if ((grp_dut_Pipeline_VITIS_LOOP_38_1_fu_148_ap_done = ap_const_logic_0)) then 
            ap_ST_fsm_state4_blk <= ap_const_logic_1;
        else 
            ap_ST_fsm_state4_blk <= ap_const_logic_0;
        end if; 
    end process;


    ap_ST_fsm_state5_blk_assign_proc : process(gmem_ARREADY)
    begin
        if ((gmem_ARREADY = ap_const_logic_0)) then 
            ap_ST_fsm_state5_blk <= ap_const_logic_1;
        else 
            ap_ST_fsm_state5_blk <= ap_const_logic_0;
        end if; 
    end process;

    ap_ST_fsm_state6_blk <= ap_const_logic_0;
    ap_ST_fsm_state7_blk <= ap_const_logic_0;
    ap_ST_fsm_state8_blk <= ap_const_logic_0;
    ap_ST_fsm_state9_blk <= ap_const_logic_0;

    ap_block_state2_on_subcall_done_assign_proc : process(grp_dut_Pipeline_1_fu_130_ap_done, grp_dut_Pipeline_2_fu_136_ap_done, grp_dut_Pipeline_3_fu_142_ap_done)
    begin
                ap_block_state2_on_subcall_done <= ((grp_dut_Pipeline_3_fu_142_ap_done = ap_const_logic_0) or (grp_dut_Pipeline_2_fu_136_ap_done = ap_const_logic_0) or (grp_dut_Pipeline_1_fu_130_ap_done = ap_const_logic_0));
    end process;


    ap_done_assign_proc : process(grp_dut_Pipeline_VITIS_LOOP_73_2_fu_160_ap_done, ap_CS_fsm_state14)
    begin
        if (((grp_dut_Pipeline_VITIS_LOOP_73_2_fu_160_ap_done = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state14))) then 
            ap_done <= ap_const_logic_1;
        else 
            ap_done <= ap_const_logic_0;
        end if; 
    end process;


    ap_idle_assign_proc : process(ap_start, ap_CS_fsm_state1)
    begin
        if (((ap_start = ap_const_logic_0) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            ap_idle <= ap_const_logic_1;
        else 
            ap_idle <= ap_const_logic_0;
        end if; 
    end process;


    ap_ready_assign_proc : process(grp_dut_Pipeline_VITIS_LOOP_73_2_fu_160_ap_done, ap_CS_fsm_state14)
    begin
        if (((grp_dut_Pipeline_VITIS_LOOP_73_2_fu_160_ap_done = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state14))) then 
            ap_ready <= ap_const_logic_1;
        else 
            ap_ready <= ap_const_logic_0;
        end if; 
    end process;


    ap_rst_n_inv_assign_proc : process(ap_rst_n)
    begin
                ap_rst_n_inv <= not(ap_rst_n);
    end process;

    empty_40_fu_238_p3 <= 
        neg_ti_fu_232_p2 when (tmp_reg_277(0) = '1') else 
        tmp_4_reg_294;
    empty_fu_226_p3 <= 
        tmp_3_fu_217_p4 when (tmp_reg_277(0) = '1') else 
        tmp_4_reg_294;

    gmem_ARADDR_assign_proc : process(ap_CS_fsm_state5, gmem_addr_1_reg_283, ap_CS_fsm_state3, grp_dut_Pipeline_VITIS_LOOP_38_1_fu_148_m_axi_gmem_ARADDR, grp_dut_Pipeline_VITIS_LOOP_73_2_fu_160_m_axi_gmem_ARADDR, gmem_ARREADY, ap_CS_fsm_state4, ap_CS_fsm_state14, ap_CS_fsm_state13)
    begin
        if (((gmem_ARREADY = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state5))) then 
            gmem_ARADDR <= gmem_addr_1_reg_283;
        elsif (((ap_const_logic_1 = ap_CS_fsm_state13) or (ap_const_logic_1 = ap_CS_fsm_state14))) then 
            gmem_ARADDR <= grp_dut_Pipeline_VITIS_LOOP_73_2_fu_160_m_axi_gmem_ARADDR;
        elsif (((ap_const_logic_1 = ap_CS_fsm_state4) or (ap_const_logic_1 = ap_CS_fsm_state3))) then 
            gmem_ARADDR <= grp_dut_Pipeline_VITIS_LOOP_38_1_fu_148_m_axi_gmem_ARADDR;
        else 
            gmem_ARADDR <= "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX";
        end if; 
    end process;


    gmem_ARLEN_assign_proc : process(ap_CS_fsm_state5, ap_CS_fsm_state3, grp_dut_Pipeline_VITIS_LOOP_38_1_fu_148_m_axi_gmem_ARLEN, grp_dut_Pipeline_VITIS_LOOP_73_2_fu_160_m_axi_gmem_ARLEN, gmem_ARREADY, ap_CS_fsm_state4, ap_CS_fsm_state14, ap_CS_fsm_state13)
    begin
        if (((gmem_ARREADY = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state5))) then 
            gmem_ARLEN <= ap_const_lv32_1;
        elsif (((ap_const_logic_1 = ap_CS_fsm_state13) or (ap_const_logic_1 = ap_CS_fsm_state14))) then 
            gmem_ARLEN <= grp_dut_Pipeline_VITIS_LOOP_73_2_fu_160_m_axi_gmem_ARLEN;
        elsif (((ap_const_logic_1 = ap_CS_fsm_state4) or (ap_const_logic_1 = ap_CS_fsm_state3))) then 
            gmem_ARLEN <= grp_dut_Pipeline_VITIS_LOOP_38_1_fu_148_m_axi_gmem_ARLEN;
        else 
            gmem_ARLEN <= "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX";
        end if; 
    end process;


    gmem_ARVALID_assign_proc : process(ap_CS_fsm_state5, ap_CS_fsm_state3, grp_dut_Pipeline_VITIS_LOOP_38_1_fu_148_m_axi_gmem_ARVALID, grp_dut_Pipeline_VITIS_LOOP_73_2_fu_160_m_axi_gmem_ARVALID, gmem_ARREADY, ap_CS_fsm_state4, ap_CS_fsm_state14, ap_CS_fsm_state13)
    begin
        if (((gmem_ARREADY = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state5))) then 
            gmem_ARVALID <= ap_const_logic_1;
        elsif (((ap_const_logic_1 = ap_CS_fsm_state13) or (ap_const_logic_1 = ap_CS_fsm_state14))) then 
            gmem_ARVALID <= grp_dut_Pipeline_VITIS_LOOP_73_2_fu_160_m_axi_gmem_ARVALID;
        elsif (((ap_const_logic_1 = ap_CS_fsm_state4) or (ap_const_logic_1 = ap_CS_fsm_state3))) then 
            gmem_ARVALID <= grp_dut_Pipeline_VITIS_LOOP_38_1_fu_148_m_axi_gmem_ARVALID;
        else 
            gmem_ARVALID <= ap_const_logic_0;
        end if; 
    end process;


    gmem_AWADDR_assign_proc : process(ap_CS_fsm_state3, grp_dut_Pipeline_VITIS_LOOP_38_1_fu_148_m_axi_gmem_AWADDR, grp_dut_Pipeline_VITIS_LOOP_73_2_fu_160_m_axi_gmem_AWADDR, ap_CS_fsm_state4, ap_CS_fsm_state14, ap_CS_fsm_state13)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state13) or (ap_const_logic_1 = ap_CS_fsm_state14))) then 
            gmem_AWADDR <= grp_dut_Pipeline_VITIS_LOOP_73_2_fu_160_m_axi_gmem_AWADDR;
        elsif (((ap_const_logic_1 = ap_CS_fsm_state4) or (ap_const_logic_1 = ap_CS_fsm_state3))) then 
            gmem_AWADDR <= grp_dut_Pipeline_VITIS_LOOP_38_1_fu_148_m_axi_gmem_AWADDR;
        else 
            gmem_AWADDR <= "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX";
        end if; 
    end process;


    gmem_AWLEN_assign_proc : process(ap_CS_fsm_state3, grp_dut_Pipeline_VITIS_LOOP_38_1_fu_148_m_axi_gmem_AWLEN, grp_dut_Pipeline_VITIS_LOOP_73_2_fu_160_m_axi_gmem_AWLEN, ap_CS_fsm_state4, ap_CS_fsm_state14, ap_CS_fsm_state13)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state13) or (ap_const_logic_1 = ap_CS_fsm_state14))) then 
            gmem_AWLEN <= grp_dut_Pipeline_VITIS_LOOP_73_2_fu_160_m_axi_gmem_AWLEN;
        elsif (((ap_const_logic_1 = ap_CS_fsm_state4) or (ap_const_logic_1 = ap_CS_fsm_state3))) then 
            gmem_AWLEN <= grp_dut_Pipeline_VITIS_LOOP_38_1_fu_148_m_axi_gmem_AWLEN;
        else 
            gmem_AWLEN <= "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX";
        end if; 
    end process;


    gmem_AWVALID_assign_proc : process(ap_CS_fsm_state3, grp_dut_Pipeline_VITIS_LOOP_38_1_fu_148_m_axi_gmem_AWVALID, grp_dut_Pipeline_VITIS_LOOP_73_2_fu_160_m_axi_gmem_AWVALID, ap_CS_fsm_state4, ap_CS_fsm_state14, ap_CS_fsm_state13)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state13) or (ap_const_logic_1 = ap_CS_fsm_state14))) then 
            gmem_AWVALID <= grp_dut_Pipeline_VITIS_LOOP_73_2_fu_160_m_axi_gmem_AWVALID;
        elsif (((ap_const_logic_1 = ap_CS_fsm_state4) or (ap_const_logic_1 = ap_CS_fsm_state3))) then 
            gmem_AWVALID <= grp_dut_Pipeline_VITIS_LOOP_38_1_fu_148_m_axi_gmem_AWVALID;
        else 
            gmem_AWVALID <= ap_const_logic_0;
        end if; 
    end process;


    gmem_BREADY_assign_proc : process(ap_CS_fsm_state3, grp_dut_Pipeline_VITIS_LOOP_38_1_fu_148_m_axi_gmem_BREADY, grp_dut_Pipeline_VITIS_LOOP_73_2_fu_160_m_axi_gmem_BREADY, ap_CS_fsm_state4, ap_CS_fsm_state14, ap_CS_fsm_state13)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state13) or (ap_const_logic_1 = ap_CS_fsm_state14))) then 
            gmem_BREADY <= grp_dut_Pipeline_VITIS_LOOP_73_2_fu_160_m_axi_gmem_BREADY;
        elsif (((ap_const_logic_1 = ap_CS_fsm_state4) or (ap_const_logic_1 = ap_CS_fsm_state3))) then 
            gmem_BREADY <= grp_dut_Pipeline_VITIS_LOOP_38_1_fu_148_m_axi_gmem_BREADY;
        else 
            gmem_BREADY <= ap_const_logic_0;
        end if; 
    end process;


    gmem_RREADY_assign_proc : process(ap_CS_fsm_state12, ap_CS_fsm_state3, grp_dut_Pipeline_VITIS_LOOP_38_1_fu_148_m_axi_gmem_RREADY, grp_dut_Pipeline_VITIS_LOOP_73_2_fu_160_m_axi_gmem_RREADY, gmem_RVALID, ap_CS_fsm_state4, ap_CS_fsm_state14, ap_CS_fsm_state13)
    begin
        if (((gmem_RVALID = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state12))) then 
            gmem_RREADY <= ap_const_logic_1;
        elsif (((ap_const_logic_1 = ap_CS_fsm_state13) or (ap_const_logic_1 = ap_CS_fsm_state14))) then 
            gmem_RREADY <= grp_dut_Pipeline_VITIS_LOOP_73_2_fu_160_m_axi_gmem_RREADY;
        elsif (((ap_const_logic_1 = ap_CS_fsm_state4) or (ap_const_logic_1 = ap_CS_fsm_state3))) then 
            gmem_RREADY <= grp_dut_Pipeline_VITIS_LOOP_38_1_fu_148_m_axi_gmem_RREADY;
        else 
            gmem_RREADY <= ap_const_logic_0;
        end if; 
    end process;


    gmem_WDATA_assign_proc : process(ap_CS_fsm_state3, grp_dut_Pipeline_VITIS_LOOP_38_1_fu_148_m_axi_gmem_WDATA, grp_dut_Pipeline_VITIS_LOOP_73_2_fu_160_m_axi_gmem_WDATA, ap_CS_fsm_state4, ap_CS_fsm_state14, ap_CS_fsm_state13)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state13) or (ap_const_logic_1 = ap_CS_fsm_state14))) then 
            gmem_WDATA <= grp_dut_Pipeline_VITIS_LOOP_73_2_fu_160_m_axi_gmem_WDATA;
        elsif (((ap_const_logic_1 = ap_CS_fsm_state4) or (ap_const_logic_1 = ap_CS_fsm_state3))) then 
            gmem_WDATA <= grp_dut_Pipeline_VITIS_LOOP_38_1_fu_148_m_axi_gmem_WDATA;
        else 
            gmem_WDATA <= "XXXXXXXX";
        end if; 
    end process;


    gmem_WSTRB_assign_proc : process(ap_CS_fsm_state3, grp_dut_Pipeline_VITIS_LOOP_38_1_fu_148_m_axi_gmem_WSTRB, grp_dut_Pipeline_VITIS_LOOP_73_2_fu_160_m_axi_gmem_WSTRB, ap_CS_fsm_state4, ap_CS_fsm_state14, ap_CS_fsm_state13)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state13) or (ap_const_logic_1 = ap_CS_fsm_state14))) then 
            gmem_WSTRB <= grp_dut_Pipeline_VITIS_LOOP_73_2_fu_160_m_axi_gmem_WSTRB;
        elsif (((ap_const_logic_1 = ap_CS_fsm_state4) or (ap_const_logic_1 = ap_CS_fsm_state3))) then 
            gmem_WSTRB <= grp_dut_Pipeline_VITIS_LOOP_38_1_fu_148_m_axi_gmem_WSTRB;
        else 
            gmem_WSTRB <= "X";
        end if; 
    end process;


    gmem_WVALID_assign_proc : process(ap_CS_fsm_state3, grp_dut_Pipeline_VITIS_LOOP_38_1_fu_148_m_axi_gmem_WVALID, grp_dut_Pipeline_VITIS_LOOP_73_2_fu_160_m_axi_gmem_WVALID, ap_CS_fsm_state4, ap_CS_fsm_state14, ap_CS_fsm_state13)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state13) or (ap_const_logic_1 = ap_CS_fsm_state14))) then 
            gmem_WVALID <= grp_dut_Pipeline_VITIS_LOOP_73_2_fu_160_m_axi_gmem_WVALID;
        elsif (((ap_const_logic_1 = ap_CS_fsm_state4) or (ap_const_logic_1 = ap_CS_fsm_state3))) then 
            gmem_WVALID <= grp_dut_Pipeline_VITIS_LOOP_38_1_fu_148_m_axi_gmem_WVALID;
        else 
            gmem_WVALID <= ap_const_logic_0;
        end if; 
    end process;


    gmem_blk_n_AR_assign_proc : process(m_axi_gmem_ARREADY, ap_CS_fsm_state5)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state5)) then 
            gmem_blk_n_AR <= m_axi_gmem_ARREADY;
        else 
            gmem_blk_n_AR <= ap_const_logic_1;
        end if; 
    end process;


    gmem_blk_n_R_assign_proc : process(m_axi_gmem_RVALID, ap_CS_fsm_state12)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state12)) then 
            gmem_blk_n_R <= m_axi_gmem_RVALID;
        else 
            gmem_blk_n_R <= ap_const_logic_1;
        end if; 
    end process;

    grp_dut_Pipeline_1_fu_130_ap_start <= grp_dut_Pipeline_1_fu_130_ap_start_reg;
    grp_dut_Pipeline_2_fu_136_ap_start <= grp_dut_Pipeline_2_fu_136_ap_start_reg;
    grp_dut_Pipeline_3_fu_142_ap_start <= grp_dut_Pipeline_3_fu_142_ap_start_reg;
    grp_dut_Pipeline_VITIS_LOOP_38_1_fu_148_ap_start <= grp_dut_Pipeline_VITIS_LOOP_38_1_fu_148_ap_start_reg;
    grp_dut_Pipeline_VITIS_LOOP_73_2_fu_160_ap_start <= grp_dut_Pipeline_VITIS_LOOP_73_2_fu_160_ap_start_reg;

    grp_fu_183_ce_assign_proc : process(ap_CS_fsm_state5, ap_CS_fsm_state2, ap_CS_fsm_state3, ap_CS_fsm_state6, grp_dut_Pipeline_VITIS_LOOP_38_1_fu_148_ap_done, gmem_ARREADY, ap_CS_fsm_state4, ap_block_state2_on_subcall_done)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state6) or (ap_const_logic_1 = ap_CS_fsm_state3) or ((grp_dut_Pipeline_VITIS_LOOP_38_1_fu_148_ap_done = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state4)) or ((ap_const_boolean_0 = ap_block_state2_on_subcall_done) and (ap_const_logic_1 = ap_CS_fsm_state2)) or ((gmem_ARREADY = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state5)))) then 
            grp_fu_183_ce <= ap_const_logic_1;
        else 
            grp_fu_183_ce <= ap_const_logic_0;
        end if; 
    end process;

    grp_fu_183_p1 <= ap_const_lv65_1745D1746(34 - 1 downto 0);
    neg_mul_fu_212_p2 <= std_logic_vector(unsigned(ap_const_lv65_0) - unsigned(mul_reg_289));
    neg_ti_fu_232_p2 <= std_logic_vector(unsigned(ap_const_lv29_0) - unsigned(empty_fu_226_p3));
    next_col_idx_V_fu_250_p1 <= gmem_RDATA(3 - 1 downto 0);

    ptr_col2_address0_assign_proc : process(ap_CS_fsm_state2, grp_dut_Pipeline_2_fu_136_ptr_col2_address0, grp_dut_Pipeline_VITIS_LOOP_38_1_fu_148_ptr_col2_address0, grp_dut_Pipeline_VITIS_LOOP_73_2_fu_160_ptr_col2_address0, ap_CS_fsm_state4, ap_CS_fsm_state14)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state14)) then 
            ptr_col2_address0 <= grp_dut_Pipeline_VITIS_LOOP_73_2_fu_160_ptr_col2_address0;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state4)) then 
            ptr_col2_address0 <= grp_dut_Pipeline_VITIS_LOOP_38_1_fu_148_ptr_col2_address0;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state2)) then 
            ptr_col2_address0 <= grp_dut_Pipeline_2_fu_136_ptr_col2_address0;
        else 
            ptr_col2_address0 <= "XXX";
        end if; 
    end process;


    ptr_col2_base_address0_assign_proc : process(ap_CS_fsm_state2, grp_dut_Pipeline_3_fu_142_ptr_col2_base_address0, grp_dut_Pipeline_VITIS_LOOP_38_1_fu_148_ptr_col2_base_address0, grp_dut_Pipeline_VITIS_LOOP_73_2_fu_160_ptr_col2_base_address0, ap_CS_fsm_state4, ap_CS_fsm_state14)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state14)) then 
            ptr_col2_base_address0 <= grp_dut_Pipeline_VITIS_LOOP_73_2_fu_160_ptr_col2_base_address0;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state4)) then 
            ptr_col2_base_address0 <= grp_dut_Pipeline_VITIS_LOOP_38_1_fu_148_ptr_col2_base_address0;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state2)) then 
            ptr_col2_base_address0 <= grp_dut_Pipeline_3_fu_142_ptr_col2_base_address0;
        else 
            ptr_col2_base_address0 <= "XXX";
        end if; 
    end process;


    ptr_col2_base_ce0_assign_proc : process(ap_CS_fsm_state2, grp_dut_Pipeline_3_fu_142_ptr_col2_base_ce0, grp_dut_Pipeline_VITIS_LOOP_38_1_fu_148_ptr_col2_base_ce0, grp_dut_Pipeline_VITIS_LOOP_73_2_fu_160_ptr_col2_base_ce0, ap_CS_fsm_state4, ap_CS_fsm_state14)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state14)) then 
            ptr_col2_base_ce0 <= grp_dut_Pipeline_VITIS_LOOP_73_2_fu_160_ptr_col2_base_ce0;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state4)) then 
            ptr_col2_base_ce0 <= grp_dut_Pipeline_VITIS_LOOP_38_1_fu_148_ptr_col2_base_ce0;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state2)) then 
            ptr_col2_base_ce0 <= grp_dut_Pipeline_3_fu_142_ptr_col2_base_ce0;
        else 
            ptr_col2_base_ce0 <= ap_const_logic_0;
        end if; 
    end process;


    ptr_col2_base_d0_assign_proc : process(ap_CS_fsm_state2, grp_dut_Pipeline_3_fu_142_ptr_col2_base_d0, grp_dut_Pipeline_VITIS_LOOP_38_1_fu_148_ptr_col2_base_d0, ap_CS_fsm_state4)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state4)) then 
            ptr_col2_base_d0 <= grp_dut_Pipeline_VITIS_LOOP_38_1_fu_148_ptr_col2_base_d0;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state2)) then 
            ptr_col2_base_d0 <= grp_dut_Pipeline_3_fu_142_ptr_col2_base_d0;
        else 
            ptr_col2_base_d0 <= "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX";
        end if; 
    end process;


    ptr_col2_base_we0_assign_proc : process(ap_CS_fsm_state2, grp_dut_Pipeline_3_fu_142_ptr_col2_base_we0, grp_dut_Pipeline_VITIS_LOOP_38_1_fu_148_ptr_col2_base_we0, ap_CS_fsm_state4)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state4)) then 
            ptr_col2_base_we0 <= grp_dut_Pipeline_VITIS_LOOP_38_1_fu_148_ptr_col2_base_we0;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state2)) then 
            ptr_col2_base_we0 <= grp_dut_Pipeline_3_fu_142_ptr_col2_base_we0;
        else 
            ptr_col2_base_we0 <= ap_const_logic_0;
        end if; 
    end process;


    ptr_col2_ce0_assign_proc : process(ap_CS_fsm_state2, grp_dut_Pipeline_2_fu_136_ptr_col2_ce0, grp_dut_Pipeline_VITIS_LOOP_38_1_fu_148_ptr_col2_ce0, grp_dut_Pipeline_VITIS_LOOP_73_2_fu_160_ptr_col2_ce0, ap_CS_fsm_state4, ap_CS_fsm_state14)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state14)) then 
            ptr_col2_ce0 <= grp_dut_Pipeline_VITIS_LOOP_73_2_fu_160_ptr_col2_ce0;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state4)) then 
            ptr_col2_ce0 <= grp_dut_Pipeline_VITIS_LOOP_38_1_fu_148_ptr_col2_ce0;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state2)) then 
            ptr_col2_ce0 <= grp_dut_Pipeline_2_fu_136_ptr_col2_ce0;
        else 
            ptr_col2_ce0 <= ap_const_logic_0;
        end if; 
    end process;


    ptr_col2_d0_assign_proc : process(ap_CS_fsm_state2, grp_dut_Pipeline_2_fu_136_ptr_col2_d0, grp_dut_Pipeline_VITIS_LOOP_38_1_fu_148_ptr_col2_d0, grp_dut_Pipeline_VITIS_LOOP_73_2_fu_160_ptr_col2_d0, ap_CS_fsm_state4, ap_CS_fsm_state14)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state14)) then 
            ptr_col2_d0 <= grp_dut_Pipeline_VITIS_LOOP_73_2_fu_160_ptr_col2_d0;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state4)) then 
            ptr_col2_d0 <= grp_dut_Pipeline_VITIS_LOOP_38_1_fu_148_ptr_col2_d0;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state2)) then 
            ptr_col2_d0 <= grp_dut_Pipeline_2_fu_136_ptr_col2_d0;
        else 
            ptr_col2_d0 <= "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX";
        end if; 
    end process;


    ptr_col2_we0_assign_proc : process(ap_CS_fsm_state2, grp_dut_Pipeline_2_fu_136_ptr_col2_we0, grp_dut_Pipeline_VITIS_LOOP_38_1_fu_148_ptr_col2_we0, grp_dut_Pipeline_VITIS_LOOP_73_2_fu_160_ptr_col2_we0, ap_CS_fsm_state4, ap_CS_fsm_state14)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state14)) then 
            ptr_col2_we0 <= grp_dut_Pipeline_VITIS_LOOP_73_2_fu_160_ptr_col2_we0;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state4)) then 
            ptr_col2_we0 <= grp_dut_Pipeline_VITIS_LOOP_38_1_fu_148_ptr_col2_we0;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state2)) then 
            ptr_col2_we0 <= grp_dut_Pipeline_2_fu_136_ptr_col2_we0;
        else 
            ptr_col2_we0 <= ap_const_logic_0;
        end if; 
    end process;


    ptr_col_address0_assign_proc : process(ap_CS_fsm_state2, grp_dut_Pipeline_1_fu_130_ptr_col_address0, grp_dut_Pipeline_VITIS_LOOP_38_1_fu_148_ptr_col_address0, grp_dut_Pipeline_VITIS_LOOP_73_2_fu_160_ptr_col_address0, ap_CS_fsm_state4, ap_CS_fsm_state14)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state14)) then 
            ptr_col_address0 <= grp_dut_Pipeline_VITIS_LOOP_73_2_fu_160_ptr_col_address0;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state4)) then 
            ptr_col_address0 <= grp_dut_Pipeline_VITIS_LOOP_38_1_fu_148_ptr_col_address0;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state2)) then 
            ptr_col_address0 <= grp_dut_Pipeline_1_fu_130_ptr_col_address0;
        else 
            ptr_col_address0 <= "XXX";
        end if; 
    end process;


    ptr_col_ce0_assign_proc : process(ap_CS_fsm_state2, grp_dut_Pipeline_1_fu_130_ptr_col_ce0, grp_dut_Pipeline_VITIS_LOOP_38_1_fu_148_ptr_col_ce0, grp_dut_Pipeline_VITIS_LOOP_73_2_fu_160_ptr_col_ce0, ap_CS_fsm_state4, ap_CS_fsm_state14)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state14)) then 
            ptr_col_ce0 <= grp_dut_Pipeline_VITIS_LOOP_73_2_fu_160_ptr_col_ce0;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state4)) then 
            ptr_col_ce0 <= grp_dut_Pipeline_VITIS_LOOP_38_1_fu_148_ptr_col_ce0;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state2)) then 
            ptr_col_ce0 <= grp_dut_Pipeline_1_fu_130_ptr_col_ce0;
        else 
            ptr_col_ce0 <= ap_const_logic_0;
        end if; 
    end process;


    ptr_col_ce1_assign_proc : process(grp_dut_Pipeline_VITIS_LOOP_38_1_fu_148_ptr_col_ce1, ap_CS_fsm_state4)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state4)) then 
            ptr_col_ce1 <= grp_dut_Pipeline_VITIS_LOOP_38_1_fu_148_ptr_col_ce1;
        else 
            ptr_col_ce1 <= ap_const_logic_0;
        end if; 
    end process;


    ptr_col_d0_assign_proc : process(ap_CS_fsm_state2, grp_dut_Pipeline_1_fu_130_ptr_col_d0, grp_dut_Pipeline_VITIS_LOOP_38_1_fu_148_ptr_col_d0, grp_dut_Pipeline_VITIS_LOOP_73_2_fu_160_ptr_col_d0, ap_CS_fsm_state4, ap_CS_fsm_state14)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state14)) then 
            ptr_col_d0 <= grp_dut_Pipeline_VITIS_LOOP_73_2_fu_160_ptr_col_d0;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state4)) then 
            ptr_col_d0 <= grp_dut_Pipeline_VITIS_LOOP_38_1_fu_148_ptr_col_d0;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state2)) then 
            ptr_col_d0 <= grp_dut_Pipeline_1_fu_130_ptr_col_d0;
        else 
            ptr_col_d0 <= "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX";
        end if; 
    end process;


    ptr_col_we0_assign_proc : process(ap_CS_fsm_state2, grp_dut_Pipeline_1_fu_130_ptr_col_we0, grp_dut_Pipeline_VITIS_LOOP_38_1_fu_148_ptr_col_we0, grp_dut_Pipeline_VITIS_LOOP_73_2_fu_160_ptr_col_we0, ap_CS_fsm_state4, ap_CS_fsm_state14)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state14)) then 
            ptr_col_we0 <= grp_dut_Pipeline_VITIS_LOOP_73_2_fu_160_ptr_col_we0;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state4)) then 
            ptr_col_we0 <= grp_dut_Pipeline_VITIS_LOOP_38_1_fu_148_ptr_col_we0;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state2)) then 
            ptr_col_we0 <= grp_dut_Pipeline_1_fu_130_ptr_col_we0;
        else 
            ptr_col_we0 <= ap_const_logic_0;
        end if; 
    end process;


    ptr_col_we1_assign_proc : process(grp_dut_Pipeline_VITIS_LOOP_38_1_fu_148_ptr_col_we1, ap_CS_fsm_state4)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state4)) then 
            ptr_col_we1 <= grp_dut_Pipeline_VITIS_LOOP_38_1_fu_148_ptr_col_we1;
        else 
            ptr_col_we1 <= ap_const_logic_0;
        end if; 
    end process;

    sub_fu_244_p2 <= std_logic_vector(unsigned(empty_40_fu_238_p3) + unsigned(ap_const_lv29_1FFFFFFF));
    tmp_3_fu_217_p4 <= neg_mul_reg_300(64 downto 36);
    tmp_fu_189_p1 <= src_sz;
end behav;
